package com.gvt.main.hibernate.model;
// Generated 29-oct-2020 13:48:51 by Hibernate Tools 3.2.2.GA and Assent Architecture


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.gvt.core.domain.types.Auditable;
import com.gvt.core.domain.types.Cleanable;
import com.gvt.core.domain.types.Fillable;
import com.gvt.core.domain.types.Identificable;
import com.gvt.core.domain.types.Seleccionable;
import com.gvt.core.domain.types.Versionable;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlTransient;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * ConsultaMedicaProtocoloCie10 generated by hbm2java
 */
@Entity
@EntityListeners({ AuditingEntityListener.class })
@Table(name="consulta_medica_protocolo_cie10"
    ,schema="public"
)
public class ConsultaMedicaProtocoloCie10  implements Versionable,Seleccionable,Identificable,Fillable,Cleanable,Auditable,java.io.Serializable {


 	
 	private Long id;
 	
 	private long version;
 	
 	private ConsultaMedicaFitnessNutricion consultaMedicaFitnessNutricion;
 	
 	private ProtocoloCie10 protocoloCie10;
 	
 	private ConsultaMedicaObstetricia consultaMedicaObstetricia;
 	
 	private ConsultaMedica consultaMedica;
 	@CreatedBy
 	private String usuarioCreacion;
 	@CreatedDate
 	private LocalDateTime fechaCreacion;
 	@LastModifiedBy
 	private String usuarioModificacion;
 	@LastModifiedDate
 	private LocalDateTime fechaModificacion;

    public ConsultaMedicaProtocoloCie10() {
    	// default constructor
    }

	
    public ConsultaMedicaProtocoloCie10(ProtocoloCie10 protocoloCie10) {
        this.protocoloCie10 = protocoloCie10;
    }
    public ConsultaMedicaProtocoloCie10(ConsultaMedicaFitnessNutricion consultaMedicaFitnessNutricion, ProtocoloCie10 protocoloCie10, ConsultaMedicaObstetricia consultaMedicaObstetricia, ConsultaMedica consultaMedica, String usuarioCreacion, LocalDateTime fechaCreacion, String usuarioModificacion, LocalDateTime fechaModificacion) {
       this.consultaMedicaFitnessNutricion = consultaMedicaFitnessNutricion;
       this.protocoloCie10 = protocoloCie10;
       this.consultaMedicaObstetricia = consultaMedicaObstetricia;
       this.consultaMedica = consultaMedica;
       this.usuarioCreacion = usuarioCreacion;
       this.fechaCreacion = fechaCreacion;
       this.usuarioModificacion = usuarioModificacion;
       this.fechaModificacion = fechaModificacion;
    }
   
  @GenericGenerator(name = "consulta_medica_protocolo_cie10_seq_gen", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator",
            parameters = {
                    @Parameter(name = "sequence_name", value = "consulta_medica_protocolo_cie10_id_seq"),
                    @Parameter(name = "initial_value", value = "1"),
                    @Parameter(name = "increment_size", value = "1")
            })
  @GeneratedValue(generator = "consulta_medica_protocolo_cie10_seq_gen")
  @Id
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    @Version
    @Column(name="version", nullable=false)
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_consulta_medica_fitness_nutricion")
    public ConsultaMedicaFitnessNutricion getConsultaMedicaFitnessNutricion() {
        return this.consultaMedicaFitnessNutricion;
    }
    
    public void setConsultaMedicaFitnessNutricion(ConsultaMedicaFitnessNutricion consultaMedicaFitnessNutricion) {
        this.consultaMedicaFitnessNutricion = consultaMedicaFitnessNutricion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_protocolo_cie10", nullable=false)
    public ProtocoloCie10 getProtocoloCie10() {
        return this.protocoloCie10;
    }
    
    public void setProtocoloCie10(ProtocoloCie10 protocoloCie10) {
        this.protocoloCie10 = protocoloCie10;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_consulta_medica_obstetricia")
    public ConsultaMedicaObstetricia getConsultaMedicaObstetricia() {
        return this.consultaMedicaObstetricia;
    }
    
    public void setConsultaMedicaObstetricia(ConsultaMedicaObstetricia consultaMedicaObstetricia) {
        this.consultaMedicaObstetricia = consultaMedicaObstetricia;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_consulta_medica")
    public ConsultaMedica getConsultaMedica() {
        return this.consultaMedica;
    }
    
    public void setConsultaMedica(ConsultaMedica consultaMedica) {
        this.consultaMedica = consultaMedica;
    }
    
    @Column(name="usuario_creacion", length=64)
    public String getUsuarioCreacion() {
        return this.usuarioCreacion;
    }
    
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }
    
    @Column(name="fecha_creacion", length=29)
    public LocalDateTime getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(LocalDateTime fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    
    @Column(name="usuario_modificacion", length=64)
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    
    @Column(name="fecha_modificacion", length=29)
    public LocalDateTime getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(LocalDateTime fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    /**
     * toString
     * @return String
     */
     @Override
     public String toString() {
	  StringBuilder buffer = new StringBuilder();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("id").append("='").append(getId()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("consultaMedicaFitnessNutricion").append("='").append(getConsultaMedicaFitnessNutricion()).append("' ");			
      buffer.append("protocoloCie10").append("='").append(getProtocoloCie10()).append("' ");			
      buffer.append("consultaMedicaObstetricia").append("='").append(getConsultaMedicaObstetricia()).append("' ");			
      buffer.append("consultaMedica").append("='").append(getConsultaMedica()).append("' ");			
      buffer.append("usuarioCreacion").append("='").append(getUsuarioCreacion()).append("' ");			
      buffer.append("fechaCreacion").append("='").append(getFechaCreacion()).append("' ");			
      buffer.append("usuarioModificacion").append("='").append(getUsuarioModificacion()).append("' ");			
      buffer.append("fechaModificacion").append("='").append(getFechaModificacion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }

	@Override
	public boolean equals(Object other) {
         if (this == other) 
         	return true;
         	
		 if (other == null) 
		 	return false;
		 	
		 if (!(other instanceof ConsultaMedicaProtocoloCie10)) 
		 	return false;
		 	
		 ConsultaMedicaProtocoloCie10 castOther = ( ConsultaMedicaProtocoloCie10 ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && (this.getVersion()==castOther.getVersion());
   }
   
   @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + (int) this.getVersion();
         
         
         
         
         
         
         
         
         return result;
   }   

  // The following is extra code specified in src/main/config/templates
// Adding extra-code
	private boolean comesFromExternalDataSource = false;
	private boolean selected;
	
	@javax.persistence.Transient
    public boolean isExternalDataSource() {
		return this.comesFromExternalDataSource;
    }

    public void setExternalDataSource(boolean value) {
        this.comesFromExternalDataSource = value;
    }

	@javax.persistence.Transient
	public boolean getSelected() {
		return selected;
	}

    public void setSelected(boolean selected) {
		this.selected = selected;
    }
    
    public void cleanPOJO() {
		if(this.consultaMedicaFitnessNutricion != null &&
			(consultaMedicaFitnessNutricion.getId() == null || this.consultaMedicaFitnessNutricion.getId().longValue() == 0)) {
			consultaMedicaFitnessNutricion = null;
		}
		if(this.protocoloCie10 != null &&
			(protocoloCie10.getId() == null || this.protocoloCie10.getId().longValue() == 0)) {
			protocoloCie10 = null;
		}
		if(this.consultaMedicaObstetricia != null &&
			(consultaMedicaObstetricia.getId() == null || this.consultaMedicaObstetricia.getId().longValue() == 0)) {
			consultaMedicaObstetricia = null;
		}
		if(this.consultaMedica != null &&
			(consultaMedica.getId() == null || this.consultaMedica.getId().longValue() == 0)) {
			consultaMedica = null;
		}
    }
    
    public void fillPOJO() {
		if(this.consultaMedicaFitnessNutricion == null) {
			consultaMedicaFitnessNutricion = new ConsultaMedicaFitnessNutricion();
		}
		if(this.protocoloCie10 == null) {
			protocoloCie10 = new ProtocoloCie10();
		}
		if(this.consultaMedicaObstetricia == null) {
			consultaMedicaObstetricia = new ConsultaMedicaObstetricia();
		}
		if(this.consultaMedica == null) {
			consultaMedica = new ConsultaMedica();
		}
    }
    
    public ConsultaMedicaProtocoloCie10 createPOJO() {
		fillPOJO();
		
		return this;
	}
	
//	@PrePersist
//	public void onPrePersist() {
//		this.fechaCreacion = new Date();
//		this.usuarioCreacion = getSecurityContextPrincipal();
//	}
//
//	@PreUpdate
//	public void onPreUpdate() {
//		this.fechaModificacion = new Date();
//		this.usuarioModificacion = getSecurityContextPrincipal();
//	}
//
//	@javax.persistence.Transient
//	private String getSecurityContextPrincipal() {
//		String principal;
//		String UNKNOWN_USER = "unknownUser";
//
//		if (SecurityContextHolder.getContext().getAuthentication() == null) {
//			principal = UNKNOWN_USER;
//		} else {
//			try {
//				principal = ((User) SecurityContextHolder.getContext().getAuthentication().getPrincipal())
//						.getUsername();
//			} catch (ClassCastException e) {
//				principal = UNKNOWN_USER;
//			}
//		}
//
//		return principal;
//	}
	
  // end of extra code specified in the hbm.xml files

}

