package com.gvt.main.hibernate.model;
// Generated 12-may-2020 16:27:19 by Hibernate Tools 3.2.2.GA and Assent Architecture


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.gvt.core.domain.types.Auditable;
import com.gvt.core.domain.types.Cleanable;
import com.gvt.core.domain.types.Fillable;
import com.gvt.core.domain.types.Identificable;
import com.gvt.core.domain.types.Seleccionable;
import com.gvt.core.domain.types.Versionable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlTransient;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * Documento generated by hbm2java
 */
@Entity
@EntityListeners({ AuditingEntityListener.class })
@Table(name="documento"
    ,schema="public"
    , uniqueConstraints = {@UniqueConstraint(columnNames={"codigo_tipo_documento", "numero_documento", "id_organizacion"}), @UniqueConstraint(columnNames={"numero_control_documento", "id_organizacion"})} 
)
public class Documento  implements Versionable,Seleccionable,Identificable,Fillable,Cleanable,Auditable,java.io.Serializable {


 	
 	private Long id;
 	
 	private long version;
 	
 	private OpcionSino opcionSinoByEsImpresa;
 	
 	private Persona persona;
 	
 	private Pedido pedido;
 	
 	private StatusDocumento statusDocumento;
 	
 	private OpcionSino opcionSinoByEsAnulado;
 	
 	private OpcionSino opcionSinoByEsPagada;
 	
 	private Documento documento;
 	
 	private Organizacion organizacion;
 	
 	private String numeroDocumento;
 	
 	private String numeroControlDocumento;
 	
 	private String serieIdentificacion;
 	
 	private Date fechaElaboracionDocumento;
 	
 	private Date fechaPagadoDocumento;
 	
 	private Date fechaVencimientoDocumento;
 	
 	private Date fechaAnuladoDocumento;
 	
 	private BigDecimal montoSubtotalPedido;
 	
 	private BigDecimal montoExentoPedido;
 	
 	private BigDecimal montoGravablePedido1;
 	
 	private Float porcentajeIvaPedido1;
 	
 	private BigDecimal montoIvaPedido1;
 	
 	private BigDecimal montoGravablePedido2;
 	
 	private Float porcentajeIvaPedido2;
 	
 	private BigDecimal montoIvaPedido2;
 	
 	private BigDecimal montoGravablePedido3;
 	
 	private Float porcentajeIvaPedido3;
 	
 	private BigDecimal montoIvaPedido3;
 	
 	private BigDecimal montoGravablePedido4;
 	
 	private Float porcentajeIvaPedido4;
 	
 	private BigDecimal montoIvaPedido4;
 	
 	private BigDecimal montoGravablePedido5;
 	
 	private Float porcentajeIvaPedido5;
 	
 	private BigDecimal montoIvaPedido5;
 	
 	private BigDecimal montoTotalPedido;
 	
 	private String codigoCliente;
 	
 	private String cedulaCliente;
 	
 	private String nombreCliente;
 	
 	private String apellidoCliente;
 	
 	private String telefonoCliente;
 	
 	private String direccionCliente;
 	
 	private String codigoCategoriaCliente;
 	
 	private String nombreCategoriaCliente;
 	
 	private String codigoResponsablePago;
 	
 	private String cedulaResponsablePago;
 	
 	private String nombreResponsablePago;
 	
 	private String apellidoResponsablePago;
 	
 	private String telefonoResponsablePago;
 	
 	private String direccionResponsablePago;
 	
 	private String codigoCategoriaResponsablePago;
 	
 	private String nombreCategoriaResponsablePago;
 	
 	private String codigoCondicionPago;
 	
 	private String nombreCondicionPago;
 	
 	private String codigoTipoDocumento;
 	
 	private String nombreTipoDocumento;
 	
 	private String codigoUbicacionGeograficaEmision;
 	
 	private String nombreUbicacionGeograficaEmision;
 	
 	private String observacionesPagoDocumento;
 	@CreatedBy
 	private String usuarioCreacion;
 	@CreatedDate
 	private Date fechaCreacion;
 	@LastModifiedBy
 	private String usuarioModificacion;
 	@LastModifiedDate
 	private Date fechaModificacion;
 	
 	private Set<RegistroPagoDocumento> registroPagoDocumentos = new HashSet<RegistroPagoDocumento>(0);
 	
 	private Set<Documento> documentos = new HashSet<Documento>(0);

    public Documento() {
    	// default constructor
    }

	
    public Documento(OpcionSino opcionSinoByEsImpresa, Pedido pedido, OpcionSino opcionSinoByEsAnulado, OpcionSino opcionSinoByEsPagada, Organizacion organizacion, String numeroDocumento, String numeroControlDocumento, Date fechaElaboracionDocumento, BigDecimal montoSubtotalPedido, BigDecimal montoExentoPedido, BigDecimal montoTotalPedido, String codigoCliente, String cedulaCliente, String nombreCliente, String telefonoCliente, String direccionCliente, String codigoCategoriaCliente, String nombreCategoriaCliente, String codigoTipoDocumento, String nombreTipoDocumento, String codigoUbicacionGeograficaEmision, String nombreUbicacionGeograficaEmision) {
        this.opcionSinoByEsImpresa = opcionSinoByEsImpresa;
        this.pedido = pedido;
        this.opcionSinoByEsAnulado = opcionSinoByEsAnulado;
        this.opcionSinoByEsPagada = opcionSinoByEsPagada;
        this.organizacion = organizacion;
        this.numeroDocumento = numeroDocumento;
        this.numeroControlDocumento = numeroControlDocumento;
        this.fechaElaboracionDocumento = fechaElaboracionDocumento;
        this.montoSubtotalPedido = montoSubtotalPedido;
        this.montoExentoPedido = montoExentoPedido;
        this.montoTotalPedido = montoTotalPedido;
        this.codigoCliente = codigoCliente;
        this.cedulaCliente = cedulaCliente;
        this.nombreCliente = nombreCliente;
        this.telefonoCliente = telefonoCliente;
        this.direccionCliente = direccionCliente;
        this.codigoCategoriaCliente = codigoCategoriaCliente;
        this.nombreCategoriaCliente = nombreCategoriaCliente;
        this.codigoTipoDocumento = codigoTipoDocumento;
        this.nombreTipoDocumento = nombreTipoDocumento;
        this.codigoUbicacionGeograficaEmision = codigoUbicacionGeograficaEmision;
        this.nombreUbicacionGeograficaEmision = nombreUbicacionGeograficaEmision;
    }
    public Documento(OpcionSino opcionSinoByEsImpresa, Persona persona, Pedido pedido, StatusDocumento statusDocumento, OpcionSino opcionSinoByEsAnulado, OpcionSino opcionSinoByEsPagada, Documento documento, Organizacion organizacion, String numeroDocumento, String numeroControlDocumento, String serieIdentificacion, Date fechaElaboracionDocumento, Date fechaPagadoDocumento, Date fechaVencimientoDocumento, Date fechaAnuladoDocumento, BigDecimal montoSubtotalPedido, BigDecimal montoExentoPedido, BigDecimal montoGravablePedido1, Float porcentajeIvaPedido1, BigDecimal montoIvaPedido1, BigDecimal montoGravablePedido2, Float porcentajeIvaPedido2, BigDecimal montoIvaPedido2, BigDecimal montoGravablePedido3, Float porcentajeIvaPedido3, BigDecimal montoIvaPedido3, BigDecimal montoGravablePedido4, Float porcentajeIvaPedido4, BigDecimal montoIvaPedido4, BigDecimal montoGravablePedido5, Float porcentajeIvaPedido5, BigDecimal montoIvaPedido5, BigDecimal montoTotalPedido, String codigoCliente, String cedulaCliente, String nombreCliente, String apellidoCliente, String telefonoCliente, String direccionCliente, String codigoCategoriaCliente, String nombreCategoriaCliente, String codigoResponsablePago, String cedulaResponsablePago, String nombreResponsablePago, String apellidoResponsablePago, String telefonoResponsablePago, String direccionResponsablePago, String codigoCategoriaResponsablePago, String nombreCategoriaResponsablePago, String codigoCondicionPago, String nombreCondicionPago, String codigoTipoDocumento, String nombreTipoDocumento, String codigoUbicacionGeograficaEmision, String nombreUbicacionGeograficaEmision, String observacionesPagoDocumento, String usuarioCreacion, Date fechaCreacion, String usuarioModificacion, Date fechaModificacion, Set<RegistroPagoDocumento> registroPagoDocumentos, Set<Documento> documentos) {
       this.opcionSinoByEsImpresa = opcionSinoByEsImpresa;
       this.persona = persona;
       this.pedido = pedido;
       this.statusDocumento = statusDocumento;
       this.opcionSinoByEsAnulado = opcionSinoByEsAnulado;
       this.opcionSinoByEsPagada = opcionSinoByEsPagada;
       this.documento = documento;
       this.organizacion = organizacion;
       this.numeroDocumento = numeroDocumento;
       this.numeroControlDocumento = numeroControlDocumento;
       this.serieIdentificacion = serieIdentificacion;
       this.fechaElaboracionDocumento = fechaElaboracionDocumento;
       this.fechaPagadoDocumento = fechaPagadoDocumento;
       this.fechaVencimientoDocumento = fechaVencimientoDocumento;
       this.fechaAnuladoDocumento = fechaAnuladoDocumento;
       this.montoSubtotalPedido = montoSubtotalPedido;
       this.montoExentoPedido = montoExentoPedido;
       this.montoGravablePedido1 = montoGravablePedido1;
       this.porcentajeIvaPedido1 = porcentajeIvaPedido1;
       this.montoIvaPedido1 = montoIvaPedido1;
       this.montoGravablePedido2 = montoGravablePedido2;
       this.porcentajeIvaPedido2 = porcentajeIvaPedido2;
       this.montoIvaPedido2 = montoIvaPedido2;
       this.montoGravablePedido3 = montoGravablePedido3;
       this.porcentajeIvaPedido3 = porcentajeIvaPedido3;
       this.montoIvaPedido3 = montoIvaPedido3;
       this.montoGravablePedido4 = montoGravablePedido4;
       this.porcentajeIvaPedido4 = porcentajeIvaPedido4;
       this.montoIvaPedido4 = montoIvaPedido4;
       this.montoGravablePedido5 = montoGravablePedido5;
       this.porcentajeIvaPedido5 = porcentajeIvaPedido5;
       this.montoIvaPedido5 = montoIvaPedido5;
       this.montoTotalPedido = montoTotalPedido;
       this.codigoCliente = codigoCliente;
       this.cedulaCliente = cedulaCliente;
       this.nombreCliente = nombreCliente;
       this.apellidoCliente = apellidoCliente;
       this.telefonoCliente = telefonoCliente;
       this.direccionCliente = direccionCliente;
       this.codigoCategoriaCliente = codigoCategoriaCliente;
       this.nombreCategoriaCliente = nombreCategoriaCliente;
       this.codigoResponsablePago = codigoResponsablePago;
       this.cedulaResponsablePago = cedulaResponsablePago;
       this.nombreResponsablePago = nombreResponsablePago;
       this.apellidoResponsablePago = apellidoResponsablePago;
       this.telefonoResponsablePago = telefonoResponsablePago;
       this.direccionResponsablePago = direccionResponsablePago;
       this.codigoCategoriaResponsablePago = codigoCategoriaResponsablePago;
       this.nombreCategoriaResponsablePago = nombreCategoriaResponsablePago;
       this.codigoCondicionPago = codigoCondicionPago;
       this.nombreCondicionPago = nombreCondicionPago;
       this.codigoTipoDocumento = codigoTipoDocumento;
       this.nombreTipoDocumento = nombreTipoDocumento;
       this.codigoUbicacionGeograficaEmision = codigoUbicacionGeograficaEmision;
       this.nombreUbicacionGeograficaEmision = nombreUbicacionGeograficaEmision;
       this.observacionesPagoDocumento = observacionesPagoDocumento;
       this.usuarioCreacion = usuarioCreacion;
       this.fechaCreacion = fechaCreacion;
       this.usuarioModificacion = usuarioModificacion;
       this.fechaModificacion = fechaModificacion;
       this.registroPagoDocumentos = registroPagoDocumentos;
       this.documentos = documentos;
    }
   
  @GenericGenerator(name = "documento_seq_gen", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator",
            parameters = {
                    @Parameter(name = "sequence_name", value = "documento_id_seq"),
                    @Parameter(name = "initial_value", value = "1"),
                    @Parameter(name = "increment_size", value = "1")
            })
  @GeneratedValue(generator = "documento_seq_gen")
  @Id
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    @Version
    @Column(name="version", nullable=false)
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="es_impresa", nullable=false)
    public OpcionSino getOpcionSinoByEsImpresa() {
        return this.opcionSinoByEsImpresa;
    }
    
    public void setOpcionSinoByEsImpresa(OpcionSino opcionSinoByEsImpresa) {
        this.opcionSinoByEsImpresa = opcionSinoByEsImpresa;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_persona_vendedor")
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pedido", nullable=false)
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_status_documento")
    public StatusDocumento getStatusDocumento() {
        return this.statusDocumento;
    }
    
    public void setStatusDocumento(StatusDocumento statusDocumento) {
        this.statusDocumento = statusDocumento;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="es_anulado", nullable=false)
    public OpcionSino getOpcionSinoByEsAnulado() {
        return this.opcionSinoByEsAnulado;
    }
    
    public void setOpcionSinoByEsAnulado(OpcionSino opcionSinoByEsAnulado) {
        this.opcionSinoByEsAnulado = opcionSinoByEsAnulado;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="es_pagada", nullable=false)
    public OpcionSino getOpcionSinoByEsPagada() {
        return this.opcionSinoByEsPagada;
    }
    
    public void setOpcionSinoByEsPagada(OpcionSino opcionSinoByEsPagada) {
        this.opcionSinoByEsPagada = opcionSinoByEsPagada;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_documento_referenciado")
    public Documento getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(Documento documento) {
        this.documento = documento;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_organizacion", nullable=false)
    public Organizacion getOrganizacion() {
        return this.organizacion;
    }
    
    public void setOrganizacion(Organizacion organizacion) {
        this.organizacion = organizacion;
    }
    
    @Column(name="numero_documento", nullable=false, length=16)
    public String getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }
    
    @Column(name="numero_control_documento", nullable=false, length=16)
    public String getNumeroControlDocumento() {
        return this.numeroControlDocumento;
    }
    
    public void setNumeroControlDocumento(String numeroControlDocumento) {
        this.numeroControlDocumento = numeroControlDocumento;
    }
    
    @Column(name="serie_identificacion", length=2)
    public String getSerieIdentificacion() {
        return this.serieIdentificacion;
    }
    
    public void setSerieIdentificacion(String serieIdentificacion) {
        this.serieIdentificacion = serieIdentificacion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_elaboracion_documento", nullable=false, length=29)
    public Date getFechaElaboracionDocumento() {
        return this.fechaElaboracionDocumento;
    }
    
    public void setFechaElaboracionDocumento(Date fechaElaboracionDocumento) {
        this.fechaElaboracionDocumento = fechaElaboracionDocumento;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_pagado_documento", length=29)
    public Date getFechaPagadoDocumento() {
        return this.fechaPagadoDocumento;
    }
    
    public void setFechaPagadoDocumento(Date fechaPagadoDocumento) {
        this.fechaPagadoDocumento = fechaPagadoDocumento;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_vencimiento_documento", length=29)
    public Date getFechaVencimientoDocumento() {
        return this.fechaVencimientoDocumento;
    }
    
    public void setFechaVencimientoDocumento(Date fechaVencimientoDocumento) {
        this.fechaVencimientoDocumento = fechaVencimientoDocumento;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_anulado_documento", length=29)
    public Date getFechaAnuladoDocumento() {
        return this.fechaAnuladoDocumento;
    }
    
    public void setFechaAnuladoDocumento(Date fechaAnuladoDocumento) {
        this.fechaAnuladoDocumento = fechaAnuladoDocumento;
    }
    
    @Column(name="monto_subtotal_pedido", nullable=false, precision=22)
    public BigDecimal getMontoSubtotalPedido() {
        return this.montoSubtotalPedido;
    }
    
    public void setMontoSubtotalPedido(BigDecimal montoSubtotalPedido) {
        this.montoSubtotalPedido = montoSubtotalPedido;
    }
    
    @Column(name="monto_exento_pedido", nullable=false, precision=22)
    public BigDecimal getMontoExentoPedido() {
        return this.montoExentoPedido;
    }
    
    public void setMontoExentoPedido(BigDecimal montoExentoPedido) {
        this.montoExentoPedido = montoExentoPedido;
    }
    
    @Column(name="monto_gravable_pedido1", precision=22)
    public BigDecimal getMontoGravablePedido1() {
        return this.montoGravablePedido1;
    }
    
    public void setMontoGravablePedido1(BigDecimal montoGravablePedido1) {
        this.montoGravablePedido1 = montoGravablePedido1;
    }
    
    @Column(name="porcentaje_iva_pedido1", precision=8, scale=8)
    public Float getPorcentajeIvaPedido1() {
        return this.porcentajeIvaPedido1;
    }
    
    public void setPorcentajeIvaPedido1(Float porcentajeIvaPedido1) {
        this.porcentajeIvaPedido1 = porcentajeIvaPedido1;
    }
    
    @Column(name="monto_iva_pedido1", precision=22)
    public BigDecimal getMontoIvaPedido1() {
        return this.montoIvaPedido1;
    }
    
    public void setMontoIvaPedido1(BigDecimal montoIvaPedido1) {
        this.montoIvaPedido1 = montoIvaPedido1;
    }
    
    @Column(name="monto_gravable_pedido2", precision=22)
    public BigDecimal getMontoGravablePedido2() {
        return this.montoGravablePedido2;
    }
    
    public void setMontoGravablePedido2(BigDecimal montoGravablePedido2) {
        this.montoGravablePedido2 = montoGravablePedido2;
    }
    
    @Column(name="porcentaje_iva_pedido2", precision=8, scale=8)
    public Float getPorcentajeIvaPedido2() {
        return this.porcentajeIvaPedido2;
    }
    
    public void setPorcentajeIvaPedido2(Float porcentajeIvaPedido2) {
        this.porcentajeIvaPedido2 = porcentajeIvaPedido2;
    }
    
    @Column(name="monto_iva_pedido2", precision=22)
    public BigDecimal getMontoIvaPedido2() {
        return this.montoIvaPedido2;
    }
    
    public void setMontoIvaPedido2(BigDecimal montoIvaPedido2) {
        this.montoIvaPedido2 = montoIvaPedido2;
    }
    
    @Column(name="monto_gravable_pedido3", precision=22)
    public BigDecimal getMontoGravablePedido3() {
        return this.montoGravablePedido3;
    }
    
    public void setMontoGravablePedido3(BigDecimal montoGravablePedido3) {
        this.montoGravablePedido3 = montoGravablePedido3;
    }
    
    @Column(name="porcentaje_iva_pedido3", precision=8, scale=8)
    public Float getPorcentajeIvaPedido3() {
        return this.porcentajeIvaPedido3;
    }
    
    public void setPorcentajeIvaPedido3(Float porcentajeIvaPedido3) {
        this.porcentajeIvaPedido3 = porcentajeIvaPedido3;
    }
    
    @Column(name="monto_iva_pedido3", precision=22)
    public BigDecimal getMontoIvaPedido3() {
        return this.montoIvaPedido3;
    }
    
    public void setMontoIvaPedido3(BigDecimal montoIvaPedido3) {
        this.montoIvaPedido3 = montoIvaPedido3;
    }
    
    @Column(name="monto_gravable_pedido4", precision=22)
    public BigDecimal getMontoGravablePedido4() {
        return this.montoGravablePedido4;
    }
    
    public void setMontoGravablePedido4(BigDecimal montoGravablePedido4) {
        this.montoGravablePedido4 = montoGravablePedido4;
    }
    
    @Column(name="porcentaje_iva_pedido4", precision=8, scale=8)
    public Float getPorcentajeIvaPedido4() {
        return this.porcentajeIvaPedido4;
    }
    
    public void setPorcentajeIvaPedido4(Float porcentajeIvaPedido4) {
        this.porcentajeIvaPedido4 = porcentajeIvaPedido4;
    }
    
    @Column(name="monto_iva_pedido4", precision=22)
    public BigDecimal getMontoIvaPedido4() {
        return this.montoIvaPedido4;
    }
    
    public void setMontoIvaPedido4(BigDecimal montoIvaPedido4) {
        this.montoIvaPedido4 = montoIvaPedido4;
    }
    
    @Column(name="monto_gravable_pedido5", precision=22)
    public BigDecimal getMontoGravablePedido5() {
        return this.montoGravablePedido5;
    }
    
    public void setMontoGravablePedido5(BigDecimal montoGravablePedido5) {
        this.montoGravablePedido5 = montoGravablePedido5;
    }
    
    @Column(name="porcentaje_iva_pedido5", precision=8, scale=8)
    public Float getPorcentajeIvaPedido5() {
        return this.porcentajeIvaPedido5;
    }
    
    public void setPorcentajeIvaPedido5(Float porcentajeIvaPedido5) {
        this.porcentajeIvaPedido5 = porcentajeIvaPedido5;
    }
    
    @Column(name="monto_iva_pedido5", precision=22)
    public BigDecimal getMontoIvaPedido5() {
        return this.montoIvaPedido5;
    }
    
    public void setMontoIvaPedido5(BigDecimal montoIvaPedido5) {
        this.montoIvaPedido5 = montoIvaPedido5;
    }
    
    @Column(name="monto_total_pedido", nullable=false, precision=22)
    public BigDecimal getMontoTotalPedido() {
        return this.montoTotalPedido;
    }
    
    public void setMontoTotalPedido(BigDecimal montoTotalPedido) {
        this.montoTotalPedido = montoTotalPedido;
    }
    
    @Column(name="codigo_cliente", nullable=false, length=16)
    public String getCodigoCliente() {
        return this.codigoCliente;
    }
    
    public void setCodigoCliente(String codigoCliente) {
        this.codigoCliente = codigoCliente;
    }
    
    @Column(name="cedula_cliente", nullable=false, length=64)
    public String getCedulaCliente() {
        return this.cedulaCliente;
    }
    
    public void setCedulaCliente(String cedulaCliente) {
        this.cedulaCliente = cedulaCliente;
    }
    
    @Column(name="nombre_cliente", nullable=false, length=64)
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    
    @Column(name="apellido_cliente", length=64)
    public String getApellidoCliente() {
        return this.apellidoCliente;
    }
    
    public void setApellidoCliente(String apellidoCliente) {
        this.apellidoCliente = apellidoCliente;
    }
    
    @Column(name="telefono_cliente", nullable=false, length=32)
    public String getTelefonoCliente() {
        return this.telefonoCliente;
    }
    
    public void setTelefonoCliente(String telefonoCliente) {
        this.telefonoCliente = telefonoCliente;
    }
    
    @Column(name="direccion_cliente", nullable=false)
    public String getDireccionCliente() {
        return this.direccionCliente;
    }
    
    public void setDireccionCliente(String direccionCliente) {
        this.direccionCliente = direccionCliente;
    }
    
    @Column(name="codigo_categoria_cliente", nullable=false, length=16)
    public String getCodigoCategoriaCliente() {
        return this.codigoCategoriaCliente;
    }
    
    public void setCodigoCategoriaCliente(String codigoCategoriaCliente) {
        this.codigoCategoriaCliente = codigoCategoriaCliente;
    }
    
    @Column(name="nombre_categoria_cliente", nullable=false, length=64)
    public String getNombreCategoriaCliente() {
        return this.nombreCategoriaCliente;
    }
    
    public void setNombreCategoriaCliente(String nombreCategoriaCliente) {
        this.nombreCategoriaCliente = nombreCategoriaCliente;
    }
    
    @Column(name="codigo_responsable_pago", length=16)
    public String getCodigoResponsablePago() {
        return this.codigoResponsablePago;
    }
    
    public void setCodigoResponsablePago(String codigoResponsablePago) {
        this.codigoResponsablePago = codigoResponsablePago;
    }
    
    @Column(name="cedula_responsable_pago", length=64)
    public String getCedulaResponsablePago() {
        return this.cedulaResponsablePago;
    }
    
    public void setCedulaResponsablePago(String cedulaResponsablePago) {
        this.cedulaResponsablePago = cedulaResponsablePago;
    }
    
    @Column(name="nombre_responsable_pago", length=64)
    public String getNombreResponsablePago() {
        return this.nombreResponsablePago;
    }
    
    public void setNombreResponsablePago(String nombreResponsablePago) {
        this.nombreResponsablePago = nombreResponsablePago;
    }
    
    @Column(name="apellido_responsable_pago", length=64)
    public String getApellidoResponsablePago() {
        return this.apellidoResponsablePago;
    }
    
    public void setApellidoResponsablePago(String apellidoResponsablePago) {
        this.apellidoResponsablePago = apellidoResponsablePago;
    }
    
    @Column(name="telefono_responsable_pago", length=32)
    public String getTelefonoResponsablePago() {
        return this.telefonoResponsablePago;
    }
    
    public void setTelefonoResponsablePago(String telefonoResponsablePago) {
        this.telefonoResponsablePago = telefonoResponsablePago;
    }
    
    @Column(name="direccion_responsable_pago")
    public String getDireccionResponsablePago() {
        return this.direccionResponsablePago;
    }
    
    public void setDireccionResponsablePago(String direccionResponsablePago) {
        this.direccionResponsablePago = direccionResponsablePago;
    }
    
    @Column(name="codigo_categoria_responsable_pago", length=16)
    public String getCodigoCategoriaResponsablePago() {
        return this.codigoCategoriaResponsablePago;
    }
    
    public void setCodigoCategoriaResponsablePago(String codigoCategoriaResponsablePago) {
        this.codigoCategoriaResponsablePago = codigoCategoriaResponsablePago;
    }
    
    @Column(name="nombre_categoria_responsable_pago", length=64)
    public String getNombreCategoriaResponsablePago() {
        return this.nombreCategoriaResponsablePago;
    }
    
    public void setNombreCategoriaResponsablePago(String nombreCategoriaResponsablePago) {
        this.nombreCategoriaResponsablePago = nombreCategoriaResponsablePago;
    }
    
    @Column(name="codigo_condicion_pago", length=16)
    public String getCodigoCondicionPago() {
        return this.codigoCondicionPago;
    }
    
    public void setCodigoCondicionPago(String codigoCondicionPago) {
        this.codigoCondicionPago = codigoCondicionPago;
    }
    
    @Column(name="nombre_condicion_pago", length=64)
    public String getNombreCondicionPago() {
        return this.nombreCondicionPago;
    }
    
    public void setNombreCondicionPago(String nombreCondicionPago) {
        this.nombreCondicionPago = nombreCondicionPago;
    }
    
    @Column(name="codigo_tipo_documento", nullable=false, length=16)
    public String getCodigoTipoDocumento() {
        return this.codigoTipoDocumento;
    }
    
    public void setCodigoTipoDocumento(String codigoTipoDocumento) {
        this.codigoTipoDocumento = codigoTipoDocumento;
    }
    
    @Column(name="nombre_tipo_documento", nullable=false, length=64)
    public String getNombreTipoDocumento() {
        return this.nombreTipoDocumento;
    }
    
    public void setNombreTipoDocumento(String nombreTipoDocumento) {
        this.nombreTipoDocumento = nombreTipoDocumento;
    }
    
    @Column(name="codigo_ubicacion_geografica_emision", nullable=false, length=16)
    public String getCodigoUbicacionGeograficaEmision() {
        return this.codigoUbicacionGeograficaEmision;
    }
    
    public void setCodigoUbicacionGeograficaEmision(String codigoUbicacionGeograficaEmision) {
        this.codigoUbicacionGeograficaEmision = codigoUbicacionGeograficaEmision;
    }
    
    @Column(name="nombre_ubicacion_geografica_emision", nullable=false, length=64)
    public String getNombreUbicacionGeograficaEmision() {
        return this.nombreUbicacionGeograficaEmision;
    }
    
    public void setNombreUbicacionGeograficaEmision(String nombreUbicacionGeograficaEmision) {
        this.nombreUbicacionGeograficaEmision = nombreUbicacionGeograficaEmision;
    }
    
    @Column(name="observaciones_pago_documento")
    public String getObservacionesPagoDocumento() {
        return this.observacionesPagoDocumento;
    }
    
    public void setObservacionesPagoDocumento(String observacionesPagoDocumento) {
        this.observacionesPagoDocumento = observacionesPagoDocumento;
    }
    
    @Column(name="usuario_creacion", length=64)
    public String getUsuarioCreacion() {
        return this.usuarioCreacion;
    }
    
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_creacion", length=29)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    
    @Column(name="usuario_modificacion", length=64)
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modificacion", length=29)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
	@XmlTransient
	@JsonIgnore
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="documento")
    public Set<RegistroPagoDocumento> getRegistroPagoDocumentos() {
        return this.registroPagoDocumentos;
    }
    
    public void setRegistroPagoDocumentos(Set<RegistroPagoDocumento> registroPagoDocumentos) {
        this.registroPagoDocumentos = registroPagoDocumentos;
    }
	@XmlTransient
	@JsonIgnore
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="documento")
    public Set<Documento> getDocumentos() {
        return this.documentos;
    }
    
    public void setDocumentos(Set<Documento> documentos) {
        this.documentos = documentos;
    }

    /**
     * toString
     * @return String
     */
     @Override
     public String toString() {
	  StringBuilder buffer = new StringBuilder();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("id").append("='").append(getId()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("opcionSinoByEsImpresa").append("='").append(getOpcionSinoByEsImpresa()).append("' ");			
      buffer.append("persona").append("='").append(getPersona()).append("' ");			
      buffer.append("pedido").append("='").append(getPedido()).append("' ");			
      buffer.append("statusDocumento").append("='").append(getStatusDocumento()).append("' ");			
      buffer.append("opcionSinoByEsAnulado").append("='").append(getOpcionSinoByEsAnulado()).append("' ");			
      buffer.append("opcionSinoByEsPagada").append("='").append(getOpcionSinoByEsPagada()).append("' ");			
      buffer.append("documento").append("='").append(getDocumento()).append("' ");			
      buffer.append("organizacion").append("='").append(getOrganizacion()).append("' ");			
      buffer.append("numeroDocumento").append("='").append(getNumeroDocumento()).append("' ");			
      buffer.append("numeroControlDocumento").append("='").append(getNumeroControlDocumento()).append("' ");			
      buffer.append("serieIdentificacion").append("='").append(getSerieIdentificacion()).append("' ");			
      buffer.append("fechaElaboracionDocumento").append("='").append(getFechaElaboracionDocumento()).append("' ");			
      buffer.append("fechaPagadoDocumento").append("='").append(getFechaPagadoDocumento()).append("' ");			
      buffer.append("fechaVencimientoDocumento").append("='").append(getFechaVencimientoDocumento()).append("' ");			
      buffer.append("fechaAnuladoDocumento").append("='").append(getFechaAnuladoDocumento()).append("' ");			
      buffer.append("montoSubtotalPedido").append("='").append(getMontoSubtotalPedido()).append("' ");			
      buffer.append("montoExentoPedido").append("='").append(getMontoExentoPedido()).append("' ");			
      buffer.append("montoGravablePedido1").append("='").append(getMontoGravablePedido1()).append("' ");			
      buffer.append("porcentajeIvaPedido1").append("='").append(getPorcentajeIvaPedido1()).append("' ");			
      buffer.append("montoIvaPedido1").append("='").append(getMontoIvaPedido1()).append("' ");			
      buffer.append("montoGravablePedido2").append("='").append(getMontoGravablePedido2()).append("' ");			
      buffer.append("porcentajeIvaPedido2").append("='").append(getPorcentajeIvaPedido2()).append("' ");			
      buffer.append("montoIvaPedido2").append("='").append(getMontoIvaPedido2()).append("' ");			
      buffer.append("montoGravablePedido3").append("='").append(getMontoGravablePedido3()).append("' ");			
      buffer.append("porcentajeIvaPedido3").append("='").append(getPorcentajeIvaPedido3()).append("' ");			
      buffer.append("montoIvaPedido3").append("='").append(getMontoIvaPedido3()).append("' ");			
      buffer.append("montoGravablePedido4").append("='").append(getMontoGravablePedido4()).append("' ");			
      buffer.append("porcentajeIvaPedido4").append("='").append(getPorcentajeIvaPedido4()).append("' ");			
      buffer.append("montoIvaPedido4").append("='").append(getMontoIvaPedido4()).append("' ");			
      buffer.append("montoGravablePedido5").append("='").append(getMontoGravablePedido5()).append("' ");			
      buffer.append("porcentajeIvaPedido5").append("='").append(getPorcentajeIvaPedido5()).append("' ");			
      buffer.append("montoIvaPedido5").append("='").append(getMontoIvaPedido5()).append("' ");			
      buffer.append("montoTotalPedido").append("='").append(getMontoTotalPedido()).append("' ");			
      buffer.append("codigoCliente").append("='").append(getCodigoCliente()).append("' ");			
      buffer.append("cedulaCliente").append("='").append(getCedulaCliente()).append("' ");			
      buffer.append("nombreCliente").append("='").append(getNombreCliente()).append("' ");			
      buffer.append("apellidoCliente").append("='").append(getApellidoCliente()).append("' ");			
      buffer.append("telefonoCliente").append("='").append(getTelefonoCliente()).append("' ");			
      buffer.append("direccionCliente").append("='").append(getDireccionCliente()).append("' ");			
      buffer.append("codigoCategoriaCliente").append("='").append(getCodigoCategoriaCliente()).append("' ");			
      buffer.append("nombreCategoriaCliente").append("='").append(getNombreCategoriaCliente()).append("' ");			
      buffer.append("codigoResponsablePago").append("='").append(getCodigoResponsablePago()).append("' ");			
      buffer.append("cedulaResponsablePago").append("='").append(getCedulaResponsablePago()).append("' ");			
      buffer.append("nombreResponsablePago").append("='").append(getNombreResponsablePago()).append("' ");			
      buffer.append("apellidoResponsablePago").append("='").append(getApellidoResponsablePago()).append("' ");			
      buffer.append("telefonoResponsablePago").append("='").append(getTelefonoResponsablePago()).append("' ");			
      buffer.append("direccionResponsablePago").append("='").append(getDireccionResponsablePago()).append("' ");			
      buffer.append("codigoCategoriaResponsablePago").append("='").append(getCodigoCategoriaResponsablePago()).append("' ");			
      buffer.append("nombreCategoriaResponsablePago").append("='").append(getNombreCategoriaResponsablePago()).append("' ");			
      buffer.append("codigoCondicionPago").append("='").append(getCodigoCondicionPago()).append("' ");			
      buffer.append("nombreCondicionPago").append("='").append(getNombreCondicionPago()).append("' ");			
      buffer.append("codigoTipoDocumento").append("='").append(getCodigoTipoDocumento()).append("' ");			
      buffer.append("nombreTipoDocumento").append("='").append(getNombreTipoDocumento()).append("' ");			
      buffer.append("codigoUbicacionGeograficaEmision").append("='").append(getCodigoUbicacionGeograficaEmision()).append("' ");			
      buffer.append("nombreUbicacionGeograficaEmision").append("='").append(getNombreUbicacionGeograficaEmision()).append("' ");			
      buffer.append("observacionesPagoDocumento").append("='").append(getObservacionesPagoDocumento()).append("' ");			
      buffer.append("usuarioCreacion").append("='").append(getUsuarioCreacion()).append("' ");			
      buffer.append("fechaCreacion").append("='").append(getFechaCreacion()).append("' ");			
      buffer.append("usuarioModificacion").append("='").append(getUsuarioModificacion()).append("' ");			
      buffer.append("fechaModificacion").append("='").append(getFechaModificacion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }

	@Override
	public boolean equals(Object other) {
         if (this == other) 
         	return true;
         	
		 if (other == null) 
		 	return false;
		 	
		 if (!(other instanceof Documento)) 
		 	return false;
		 	
		 Documento castOther = ( Documento ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && (this.getVersion()==castOther.getVersion());
   }
   
   @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + (int) this.getVersion();
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         return result;
   }   

  // The following is extra code specified in src/main/config/templates
// Adding extra-code
	private boolean comesFromExternalDataSource = false;
	private boolean selected;
	
	@javax.persistence.Transient
    public boolean isExternalDataSource() {
		return this.comesFromExternalDataSource;
    }

    public void setExternalDataSource(boolean value) {
        this.comesFromExternalDataSource = value;
    }

	@javax.persistence.Transient
	public boolean getSelected() {
		return selected;
	}

    public void setSelected(boolean selected) {
		this.selected = selected;
    }
    
    public void cleanPOJO() {
		if(this.opcionSinoByEsImpresa != null &&
			(opcionSinoByEsImpresa.getId() == null || this.opcionSinoByEsImpresa.getId().longValue() == 0)) {
			opcionSinoByEsImpresa = null;
		}
		if(this.persona != null &&
			(persona.getId() == null || this.persona.getId().longValue() == 0)) {
			persona = null;
		}
		if(this.pedido != null &&
			(pedido.getId() == null || this.pedido.getId().longValue() == 0)) {
			pedido = null;
		}
		if(this.statusDocumento != null &&
			(statusDocumento.getId() == null || this.statusDocumento.getId().longValue() == 0)) {
			statusDocumento = null;
		}
		if(this.opcionSinoByEsAnulado != null &&
			(opcionSinoByEsAnulado.getId() == null || this.opcionSinoByEsAnulado.getId().longValue() == 0)) {
			opcionSinoByEsAnulado = null;
		}
		if(this.opcionSinoByEsPagada != null &&
			(opcionSinoByEsPagada.getId() == null || this.opcionSinoByEsPagada.getId().longValue() == 0)) {
			opcionSinoByEsPagada = null;
		}
		if(this.documento != null &&
			(documento.getId() == null || this.documento.getId().longValue() == 0)) {
			documento = null;
		}
		if(this.organizacion != null &&
			(organizacion.getId() == null || this.organizacion.getId().longValue() == 0)) {
			organizacion = null;
		}
    }
    
    public void fillPOJO() {
		if(this.opcionSinoByEsImpresa == null) {
			opcionSinoByEsImpresa = new OpcionSino();
		}
		if(this.persona == null) {
			persona = new Persona();
		}
		if(this.pedido == null) {
			pedido = new Pedido();
		}
		if(this.statusDocumento == null) {
			statusDocumento = new StatusDocumento();
		}
		if(this.opcionSinoByEsAnulado == null) {
			opcionSinoByEsAnulado = new OpcionSino();
		}
		if(this.opcionSinoByEsPagada == null) {
			opcionSinoByEsPagada = new OpcionSino();
		}
		if(this.documento == null) {
			documento = new Documento();
		}
		if(this.organizacion == null) {
			organizacion = new Organizacion();
		}
    }
    
    public Documento createPOJO() {
		fillPOJO();
		
		return this;
	}
	
//	@PrePersist
//	public void onPrePersist() {
//		this.fechaCreacion = new Date();
//		this.usuarioCreacion = getSecurityContextPrincipal();
//	}
//
//	@PreUpdate
//	public void onPreUpdate() {
//		this.fechaModificacion = new Date();
//		this.usuarioModificacion = getSecurityContextPrincipal();
//	}
//
//	@javax.persistence.Transient
//	private String getSecurityContextPrincipal() {
//		String principal;
//		String UNKNOWN_USER = "unknownUser";
//
//		if (SecurityContextHolder.getContext().getAuthentication() == null) {
//			principal = UNKNOWN_USER;
//		} else {
//			try {
//				principal = ((User) SecurityContextHolder.getContext().getAuthentication().getPrincipal())
//						.getUsername();
//			} catch (ClassCastException e) {
//				principal = UNKNOWN_USER;
//			}
//		}
//
//		return principal;
//	}
	
  // end of extra code specified in the hbm.xml files

}

