package com.gvt.main.hibernate.model;
// Generated 24-may-2020 17:36:56 by Hibernate Tools 3.2.2.GA and Assent Architecture


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.gvt.core.domain.types.Auditable;
import com.gvt.core.domain.types.Cleanable;
import com.gvt.core.domain.types.Fillable;
import com.gvt.core.domain.types.Identificable;
import com.gvt.core.domain.types.Seleccionable;
import com.gvt.core.domain.types.Versionable;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlTransient;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * HorarioMedico generated by hbm2java
 */
@Entity
@EntityListeners({ AuditingEntityListener.class })
@Table(name="horario_medico"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames={"id_persona", "dia_semana"}) 
)
public class HorarioMedico  implements Versionable,Seleccionable,Identificable,Fillable,Cleanable,Auditable,java.io.Serializable {


 	
 	private Long id;
 	
 	private long version;
 	
 	private Organizacion organizacionByIdSedeInicio5;
 	
 	private Organizacion organizacionByIdSedeInicio4;
 	
 	private Organizacion organizacionByIdSedeInicio7;
 	
 	private Organizacion organizacionByIdSedeInicio6;
 	
 	private Organizacion organizacionByIdSedeInicio8;
 	
 	private Persona persona;
 	
 	private Organizacion organizacionByIdSedeInicio1;
 	
 	private Organizacion organizacionByIdSedeInicio3;
 	
 	private Organizacion organizacionByIdSedeInicio2;
 	
 	private String diaSemana;
 	
 	private LocalTime fechaInicio1;
 	
 	private LocalTime fechaInicio2;
 	
 	private LocalTime fechaInicio3;
 	
 	private LocalTime fechaInicio4;
 	
 	private LocalTime fechaInicio5;
 	
 	private LocalTime fechaInicio6;
 	
 	private LocalTime fechaInicio7;
 	
 	private LocalTime fechaInicio8;
 	
 	private LocalTime fechaFin1;
 	
 	private LocalTime fechaFin2;
 	
 	private LocalTime fechaFin3;
 	
 	private LocalTime fechaFin4;
 	
 	private LocalTime fechaFin5;
 	
 	private LocalTime fechaFin6;
 	
 	private LocalTime fechaFin7;
 	
 	private LocalTime fechaFin8;
 	@CreatedBy
 	private String usuarioCreacion;
 	@CreatedDate
 	private LocalDateTime fechaCreacion;
 	@LastModifiedBy
 	private String usuarioModificacion;
 	@LastModifiedDate
 	private LocalDateTime fechaModificacion;
 	
 	private Set<HorarioMedicoCota> horarioMedicoCotas = new HashSet<HorarioMedicoCota>(0);

    public HorarioMedico() {
    	// default constructor
    }

	
    public HorarioMedico(Persona persona) {
        this.persona = persona;
    }
    public HorarioMedico(Organizacion organizacionByIdSedeInicio5, Organizacion organizacionByIdSedeInicio4, Organizacion organizacionByIdSedeInicio7, Organizacion organizacionByIdSedeInicio6, Organizacion organizacionByIdSedeInicio8, Persona persona, Organizacion organizacionByIdSedeInicio1, Organizacion organizacionByIdSedeInicio3, Organizacion organizacionByIdSedeInicio2, String diaSemana, LocalTime fechaInicio1, LocalTime fechaInicio2, LocalTime fechaInicio3, LocalTime fechaInicio4, LocalTime fechaInicio5, LocalTime fechaInicio6, LocalTime fechaInicio7, LocalTime fechaInicio8, LocalTime fechaFin1, LocalTime fechaFin2, LocalTime fechaFin3, LocalTime fechaFin4, LocalTime fechaFin5, LocalTime fechaFin6, LocalTime fechaFin7, LocalTime fechaFin8, String usuarioCreacion, LocalDateTime fechaCreacion, String usuarioModificacion, LocalDateTime fechaModificacion, Set<HorarioMedicoCota> horarioMedicoCotas) {
       this.organizacionByIdSedeInicio5 = organizacionByIdSedeInicio5;
       this.organizacionByIdSedeInicio4 = organizacionByIdSedeInicio4;
       this.organizacionByIdSedeInicio7 = organizacionByIdSedeInicio7;
       this.organizacionByIdSedeInicio6 = organizacionByIdSedeInicio6;
       this.organizacionByIdSedeInicio8 = organizacionByIdSedeInicio8;
       this.persona = persona;
       this.organizacionByIdSedeInicio1 = organizacionByIdSedeInicio1;
       this.organizacionByIdSedeInicio3 = organizacionByIdSedeInicio3;
       this.organizacionByIdSedeInicio2 = organizacionByIdSedeInicio2;
       this.diaSemana = diaSemana;
       this.fechaInicio1 = fechaInicio1;
       this.fechaInicio2 = fechaInicio2;
       this.fechaInicio3 = fechaInicio3;
       this.fechaInicio4 = fechaInicio4;
       this.fechaInicio5 = fechaInicio5;
       this.fechaInicio6 = fechaInicio6;
       this.fechaInicio7 = fechaInicio7;
       this.fechaInicio8 = fechaInicio8;
       this.fechaFin1 = fechaFin1;
       this.fechaFin2 = fechaFin2;
       this.fechaFin3 = fechaFin3;
       this.fechaFin4 = fechaFin4;
       this.fechaFin5 = fechaFin5;
       this.fechaFin6 = fechaFin6;
       this.fechaFin7 = fechaFin7;
       this.fechaFin8 = fechaFin8;
       this.usuarioCreacion = usuarioCreacion;
       this.fechaCreacion = fechaCreacion;
       this.usuarioModificacion = usuarioModificacion;
       this.fechaModificacion = fechaModificacion;
       this.horarioMedicoCotas = horarioMedicoCotas;
    }
   
  @GenericGenerator(name = "horario_medico_seq_gen", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator",
            parameters = {
                    @Parameter(name = "sequence_name", value = "horario_medico_id_seq"),
                    @Parameter(name = "initial_value", value = "1"),
                    @Parameter(name = "increment_size", value = "1")
            })
  @GeneratedValue(generator = "horario_medico_seq_gen")
  @Id
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    @Version
    @Column(name="version", nullable=false)
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sede_inicio5")
    public Organizacion getOrganizacionByIdSedeInicio5() {
        return this.organizacionByIdSedeInicio5;
    }
    
    public void setOrganizacionByIdSedeInicio5(Organizacion organizacionByIdSedeInicio5) {
        this.organizacionByIdSedeInicio5 = organizacionByIdSedeInicio5;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sede_inicio4")
    public Organizacion getOrganizacionByIdSedeInicio4() {
        return this.organizacionByIdSedeInicio4;
    }
    
    public void setOrganizacionByIdSedeInicio4(Organizacion organizacionByIdSedeInicio4) {
        this.organizacionByIdSedeInicio4 = organizacionByIdSedeInicio4;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sede_inicio7")
    public Organizacion getOrganizacionByIdSedeInicio7() {
        return this.organizacionByIdSedeInicio7;
    }
    
    public void setOrganizacionByIdSedeInicio7(Organizacion organizacionByIdSedeInicio7) {
        this.organizacionByIdSedeInicio7 = organizacionByIdSedeInicio7;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sede_inicio6")
    public Organizacion getOrganizacionByIdSedeInicio6() {
        return this.organizacionByIdSedeInicio6;
    }
    
    public void setOrganizacionByIdSedeInicio6(Organizacion organizacionByIdSedeInicio6) {
        this.organizacionByIdSedeInicio6 = organizacionByIdSedeInicio6;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sede_inicio8")
    public Organizacion getOrganizacionByIdSedeInicio8() {
        return this.organizacionByIdSedeInicio8;
    }
    
    public void setOrganizacionByIdSedeInicio8(Organizacion organizacionByIdSedeInicio8) {
        this.organizacionByIdSedeInicio8 = organizacionByIdSedeInicio8;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_persona", nullable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sede_inicio1")
    public Organizacion getOrganizacionByIdSedeInicio1() {
        return this.organizacionByIdSedeInicio1;
    }
    
    public void setOrganizacionByIdSedeInicio1(Organizacion organizacionByIdSedeInicio1) {
        this.organizacionByIdSedeInicio1 = organizacionByIdSedeInicio1;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sede_inicio3")
    public Organizacion getOrganizacionByIdSedeInicio3() {
        return this.organizacionByIdSedeInicio3;
    }
    
    public void setOrganizacionByIdSedeInicio3(Organizacion organizacionByIdSedeInicio3) {
        this.organizacionByIdSedeInicio3 = organizacionByIdSedeInicio3;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sede_inicio2")
    public Organizacion getOrganizacionByIdSedeInicio2() {
        return this.organizacionByIdSedeInicio2;
    }
    
    public void setOrganizacionByIdSedeInicio2(Organizacion organizacionByIdSedeInicio2) {
        this.organizacionByIdSedeInicio2 = organizacionByIdSedeInicio2;
    }
    
    @Column(name="dia_semana")
    public String getDiaSemana() {
        return this.diaSemana;
    }
    
    public void setDiaSemana(String diaSemana) {
        this.diaSemana = diaSemana;
    }
    
    @Column(name="fecha_inicio_1", length=15)
    public LocalTime getFechaInicio1() {
        return this.fechaInicio1;
    }
    
    public void setFechaInicio1(LocalTime fechaInicio1) {
        this.fechaInicio1 = fechaInicio1;
    }
    
    @Column(name="fecha_inicio_2", length=15)
    public LocalTime getFechaInicio2() {
        return this.fechaInicio2;
    }
    
    public void setFechaInicio2(LocalTime fechaInicio2) {
        this.fechaInicio2 = fechaInicio2;
    }
    
    @Column(name="fecha_inicio_3", length=15)
    public LocalTime getFechaInicio3() {
        return this.fechaInicio3;
    }
    
    public void setFechaInicio3(LocalTime fechaInicio3) {
        this.fechaInicio3 = fechaInicio3;
    }
    
    @Column(name="fecha_inicio_4", length=15)
    public LocalTime getFechaInicio4() {
        return this.fechaInicio4;
    }
    
    public void setFechaInicio4(LocalTime fechaInicio4) {
        this.fechaInicio4 = fechaInicio4;
    }
    
    @Column(name="fecha_inicio_5", length=15)
    public LocalTime getFechaInicio5() {
        return this.fechaInicio5;
    }
    
    public void setFechaInicio5(LocalTime fechaInicio5) {
        this.fechaInicio5 = fechaInicio5;
    }
    
    @Column(name="fecha_inicio_6", length=15)
    public LocalTime getFechaInicio6() {
        return this.fechaInicio6;
    }
    
    public void setFechaInicio6(LocalTime fechaInicio6) {
        this.fechaInicio6 = fechaInicio6;
    }
    
    @Column(name="fecha_inicio_7", length=15)
    public LocalTime getFechaInicio7() {
        return this.fechaInicio7;
    }
    
    public void setFechaInicio7(LocalTime fechaInicio7) {
        this.fechaInicio7 = fechaInicio7;
    }
    
    @Column(name="fecha_inicio_8", length=15)
    public LocalTime getFechaInicio8() {
        return this.fechaInicio8;
    }
    
    public void setFechaInicio8(LocalTime fechaInicio8) {
        this.fechaInicio8 = fechaInicio8;
    }
    
    @Column(name="fecha_fin_1", length=15)
    public LocalTime getFechaFin1() {
        return this.fechaFin1;
    }
    
    public void setFechaFin1(LocalTime fechaFin1) {
        this.fechaFin1 = fechaFin1;
    }
    
    @Column(name="fecha_fin_2", length=15)
    public LocalTime getFechaFin2() {
        return this.fechaFin2;
    }
    
    public void setFechaFin2(LocalTime fechaFin2) {
        this.fechaFin2 = fechaFin2;
    }
    
    @Column(name="fecha_fin_3", length=15)
    public LocalTime getFechaFin3() {
        return this.fechaFin3;
    }
    
    public void setFechaFin3(LocalTime fechaFin3) {
        this.fechaFin3 = fechaFin3;
    }
    
    @Column(name="fecha_fin_4", length=15)
    public LocalTime getFechaFin4() {
        return this.fechaFin4;
    }
    
    public void setFechaFin4(LocalTime fechaFin4) {
        this.fechaFin4 = fechaFin4;
    }
    
    @Column(name="fecha_fin_5", length=15)
    public LocalTime getFechaFin5() {
        return this.fechaFin5;
    }
    
    public void setFechaFin5(LocalTime fechaFin5) {
        this.fechaFin5 = fechaFin5;
    }
    
    @Column(name="fecha_fin_6", length=15)
    public LocalTime getFechaFin6() {
        return this.fechaFin6;
    }
    
    public void setFechaFin6(LocalTime fechaFin6) {
        this.fechaFin6 = fechaFin6;
    }
    
    @Column(name="fecha_fin_7", length=15)
    public LocalTime getFechaFin7() {
        return this.fechaFin7;
    }
    
    public void setFechaFin7(LocalTime fechaFin7) {
        this.fechaFin7 = fechaFin7;
    }
    
    @Column(name="fecha_fin_8", length=15)
    public LocalTime getFechaFin8() {
        return this.fechaFin8;
    }
    
    public void setFechaFin8(LocalTime fechaFin8) {
        this.fechaFin8 = fechaFin8;
    }
    
    @Column(name="usuario_creacion", length=64)
    public String getUsuarioCreacion() {
        return this.usuarioCreacion;
    }
    
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }
    
    @Column(name="fecha_creacion", length=29)
    public LocalDateTime getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(LocalDateTime fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    
    @Column(name="usuario_modificacion", length=64)
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    
    @Column(name="fecha_modificacion", length=29)
    public LocalDateTime getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(LocalDateTime fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
	@XmlTransient
	@JsonIgnore
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="horarioMedico")
    public Set<HorarioMedicoCota> getHorarioMedicoCotas() {
        return this.horarioMedicoCotas;
    }
    
    public void setHorarioMedicoCotas(Set<HorarioMedicoCota> horarioMedicoCotas) {
        this.horarioMedicoCotas = horarioMedicoCotas;
    }

    /**
     * toString
     * @return String
     */
     @Override
     public String toString() {
	  StringBuilder buffer = new StringBuilder();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("id").append("='").append(getId()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("organizacionByIdSedeInicio5").append("='").append(getOrganizacionByIdSedeInicio5()).append("' ");			
      buffer.append("organizacionByIdSedeInicio4").append("='").append(getOrganizacionByIdSedeInicio4()).append("' ");			
      buffer.append("organizacionByIdSedeInicio7").append("='").append(getOrganizacionByIdSedeInicio7()).append("' ");			
      buffer.append("organizacionByIdSedeInicio6").append("='").append(getOrganizacionByIdSedeInicio6()).append("' ");			
      buffer.append("organizacionByIdSedeInicio8").append("='").append(getOrganizacionByIdSedeInicio8()).append("' ");			
      buffer.append("persona").append("='").append(getPersona()).append("' ");			
      buffer.append("organizacionByIdSedeInicio1").append("='").append(getOrganizacionByIdSedeInicio1()).append("' ");			
      buffer.append("organizacionByIdSedeInicio3").append("='").append(getOrganizacionByIdSedeInicio3()).append("' ");			
      buffer.append("organizacionByIdSedeInicio2").append("='").append(getOrganizacionByIdSedeInicio2()).append("' ");			
      buffer.append("diaSemana").append("='").append(getDiaSemana()).append("' ");			
      buffer.append("fechaInicio1").append("='").append(getFechaInicio1()).append("' ");			
      buffer.append("fechaInicio2").append("='").append(getFechaInicio2()).append("' ");			
      buffer.append("fechaInicio3").append("='").append(getFechaInicio3()).append("' ");			
      buffer.append("fechaInicio4").append("='").append(getFechaInicio4()).append("' ");			
      buffer.append("fechaInicio5").append("='").append(getFechaInicio5()).append("' ");			
      buffer.append("fechaInicio6").append("='").append(getFechaInicio6()).append("' ");			
      buffer.append("fechaInicio7").append("='").append(getFechaInicio7()).append("' ");			
      buffer.append("fechaInicio8").append("='").append(getFechaInicio8()).append("' ");			
      buffer.append("fechaFin1").append("='").append(getFechaFin1()).append("' ");			
      buffer.append("fechaFin2").append("='").append(getFechaFin2()).append("' ");			
      buffer.append("fechaFin3").append("='").append(getFechaFin3()).append("' ");			
      buffer.append("fechaFin4").append("='").append(getFechaFin4()).append("' ");			
      buffer.append("fechaFin5").append("='").append(getFechaFin5()).append("' ");			
      buffer.append("fechaFin6").append("='").append(getFechaFin6()).append("' ");			
      buffer.append("fechaFin7").append("='").append(getFechaFin7()).append("' ");			
      buffer.append("fechaFin8").append("='").append(getFechaFin8()).append("' ");			
      buffer.append("usuarioCreacion").append("='").append(getUsuarioCreacion()).append("' ");			
      buffer.append("fechaCreacion").append("='").append(getFechaCreacion()).append("' ");			
      buffer.append("usuarioModificacion").append("='").append(getUsuarioModificacion()).append("' ");			
      buffer.append("fechaModificacion").append("='").append(getFechaModificacion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }

	@Override
	public boolean equals(Object other) {
         if (this == other) 
         	return true;
         	
		 if (other == null) 
		 	return false;
		 	
		 if (!(other instanceof HorarioMedico)) 
		 	return false;
		 	
		 HorarioMedico castOther = ( HorarioMedico ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && (this.getVersion()==castOther.getVersion());
   }
   
   @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + (int) this.getVersion();
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         return result;
   }   

  // The following is extra code specified in src/main/config/templates
// Adding extra-code
	private boolean comesFromExternalDataSource = false;
	private boolean selected;
	
	@javax.persistence.Transient
    public boolean isExternalDataSource() {
		return this.comesFromExternalDataSource;
    }

    public void setExternalDataSource(boolean value) {
        this.comesFromExternalDataSource = value;
    }

	@javax.persistence.Transient
	public boolean getSelected() {
		return selected;
	}

    public void setSelected(boolean selected) {
		this.selected = selected;
    }
    
    public void cleanPOJO() {
		if(this.organizacionByIdSedeInicio5 != null &&
			(organizacionByIdSedeInicio5.getId() == null || this.organizacionByIdSedeInicio5.getId().longValue() == 0)) {
			organizacionByIdSedeInicio5 = null;
		}
		if(this.organizacionByIdSedeInicio4 != null &&
			(organizacionByIdSedeInicio4.getId() == null || this.organizacionByIdSedeInicio4.getId().longValue() == 0)) {
			organizacionByIdSedeInicio4 = null;
		}
		if(this.organizacionByIdSedeInicio7 != null &&
			(organizacionByIdSedeInicio7.getId() == null || this.organizacionByIdSedeInicio7.getId().longValue() == 0)) {
			organizacionByIdSedeInicio7 = null;
		}
		if(this.organizacionByIdSedeInicio6 != null &&
			(organizacionByIdSedeInicio6.getId() == null || this.organizacionByIdSedeInicio6.getId().longValue() == 0)) {
			organizacionByIdSedeInicio6 = null;
		}
		if(this.organizacionByIdSedeInicio8 != null &&
			(organizacionByIdSedeInicio8.getId() == null || this.organizacionByIdSedeInicio8.getId().longValue() == 0)) {
			organizacionByIdSedeInicio8 = null;
		}
		if(this.persona != null &&
			(persona.getId() == null || this.persona.getId().longValue() == 0)) {
			persona = null;
		}
		if(this.organizacionByIdSedeInicio1 != null &&
			(organizacionByIdSedeInicio1.getId() == null || this.organizacionByIdSedeInicio1.getId().longValue() == 0)) {
			organizacionByIdSedeInicio1 = null;
		}
		if(this.organizacionByIdSedeInicio3 != null &&
			(organizacionByIdSedeInicio3.getId() == null || this.organizacionByIdSedeInicio3.getId().longValue() == 0)) {
			organizacionByIdSedeInicio3 = null;
		}
		if(this.organizacionByIdSedeInicio2 != null &&
			(organizacionByIdSedeInicio2.getId() == null || this.organizacionByIdSedeInicio2.getId().longValue() == 0)) {
			organizacionByIdSedeInicio2 = null;
		}
    }
    
    public void fillPOJO() {
		if(this.organizacionByIdSedeInicio5 == null) {
			organizacionByIdSedeInicio5 = new Organizacion();
		}
		if(this.organizacionByIdSedeInicio4 == null) {
			organizacionByIdSedeInicio4 = new Organizacion();
		}
		if(this.organizacionByIdSedeInicio7 == null) {
			organizacionByIdSedeInicio7 = new Organizacion();
		}
		if(this.organizacionByIdSedeInicio6 == null) {
			organizacionByIdSedeInicio6 = new Organizacion();
		}
		if(this.organizacionByIdSedeInicio8 == null) {
			organizacionByIdSedeInicio8 = new Organizacion();
		}
		if(this.persona == null) {
			persona = new Persona();
		}
		if(this.organizacionByIdSedeInicio1 == null) {
			organizacionByIdSedeInicio1 = new Organizacion();
		}
		if(this.organizacionByIdSedeInicio3 == null) {
			organizacionByIdSedeInicio3 = new Organizacion();
		}
		if(this.organizacionByIdSedeInicio2 == null) {
			organizacionByIdSedeInicio2 = new Organizacion();
		}
    }
    
    public HorarioMedico createPOJO() {
		fillPOJO();
		
		return this;
	}
	
//	@PrePersist
//	public void onPrePersist() {
//		this.fechaCreacion = new Date();
//		this.usuarioCreacion = getSecurityContextPrincipal();
//	}
//
//	@PreUpdate
//	public void onPreUpdate() {
//		this.fechaModificacion = new Date();
//		this.usuarioModificacion = getSecurityContextPrincipal();
//	}
//
//	@javax.persistence.Transient
//	private String getSecurityContextPrincipal() {
//		String principal;
//		String UNKNOWN_USER = "unknownUser";
//
//		if (SecurityContextHolder.getContext().getAuthentication() == null) {
//			principal = UNKNOWN_USER;
//		} else {
//			try {
//				principal = ((User) SecurityContextHolder.getContext().getAuthentication().getPrincipal())
//						.getUsername();
//			} catch (ClassCastException e) {
//				principal = UNKNOWN_USER;
//			}
//		}
//
//		return principal;
//	}
	
  // end of extra code specified in the hbm.xml files

}

