package com.gvt.main.hibernate.model;
// Generated 09-feb-2020 20:04:15 by Hibernate Tools 3.2.2.GA and Assent Architecture


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.gvt.core.domain.types.Auditable;
import com.gvt.core.domain.types.Cleanable;
import com.gvt.core.domain.types.Fillable;
import com.gvt.core.domain.types.Identificable;
import com.gvt.core.domain.types.Seleccionable;
import com.gvt.core.domain.types.Versionable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlTransient;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * RenglonCompras generated by hbm2java
 */
@Entity
@EntityListeners({ AuditingEntityListener.class })
@Table(name="renglon_compras"
    ,schema="public"
)
public class RenglonCompras  implements Versionable,Seleccionable,Identificable,Fillable,Cleanable,Auditable,java.io.Serializable {


 	
 	private Long id;
 	
 	private long version;
 	
 	private OpcionSino opcionSino;
 	
 	private Compras compras;
 	
 	private String codigoTipoProducto;
 	
 	private String nombreTipoProducto;
 	
 	private String lote;
 	
 	private Date fechaExpedicion;
 	
 	private Date fechaVencimiento;
 	
 	private String descripcionRenglonCompras;
 	
 	private float porcentajeIva;
 	
 	private double cantidadRenglonCompras;
 	
 	private BigDecimal precioTipoProducto;
 	
 	private BigDecimal totalRenglonCompras;
 	@CreatedBy
 	private String usuarioCreacion;
 	@CreatedDate
 	private Date fechaCreacion;
 	@LastModifiedBy
 	private String usuarioModificacion;
 	@LastModifiedDate
 	private Date fechaModificacion;

    public RenglonCompras() {
    	// default constructor
    }

	
    public RenglonCompras(OpcionSino opcionSino, Compras compras, String codigoTipoProducto, String nombreTipoProducto, float porcentajeIva, double cantidadRenglonCompras, BigDecimal precioTipoProducto, BigDecimal totalRenglonCompras) {
        this.opcionSino = opcionSino;
        this.compras = compras;
        this.codigoTipoProducto = codigoTipoProducto;
        this.nombreTipoProducto = nombreTipoProducto;
        this.porcentajeIva = porcentajeIva;
        this.cantidadRenglonCompras = cantidadRenglonCompras;
        this.precioTipoProducto = precioTipoProducto;
        this.totalRenglonCompras = totalRenglonCompras;
    }
    public RenglonCompras(OpcionSino opcionSino, Compras compras, String codigoTipoProducto, String nombreTipoProducto, String lote, Date fechaExpedicion, Date fechaVencimiento, String descripcionRenglonCompras, float porcentajeIva, double cantidadRenglonCompras, BigDecimal precioTipoProducto, BigDecimal totalRenglonCompras, String usuarioCreacion, Date fechaCreacion, String usuarioModificacion, Date fechaModificacion) {
       this.opcionSino = opcionSino;
       this.compras = compras;
       this.codigoTipoProducto = codigoTipoProducto;
       this.nombreTipoProducto = nombreTipoProducto;
       this.lote = lote;
       this.fechaExpedicion = fechaExpedicion;
       this.fechaVencimiento = fechaVencimiento;
       this.descripcionRenglonCompras = descripcionRenglonCompras;
       this.porcentajeIva = porcentajeIva;
       this.cantidadRenglonCompras = cantidadRenglonCompras;
       this.precioTipoProducto = precioTipoProducto;
       this.totalRenglonCompras = totalRenglonCompras;
       this.usuarioCreacion = usuarioCreacion;
       this.fechaCreacion = fechaCreacion;
       this.usuarioModificacion = usuarioModificacion;
       this.fechaModificacion = fechaModificacion;
    }
   
  @GenericGenerator(name = "renglon_compras_seq_gen", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator",
            parameters = {
                    @Parameter(name = "sequence_name", value = "renglon_compras_id_seq"),
                    @Parameter(name = "initial_value", value = "1"),
                    @Parameter(name = "increment_size", value = "1")
            })
  @GeneratedValue(generator = "renglon_compras_seq_gen")
  @Id
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    @Version
    @Column(name="version", nullable=false)
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="es_exento", nullable=false)
    public OpcionSino getOpcionSino() {
        return this.opcionSino;
    }
    
    public void setOpcionSino(OpcionSino opcionSino) {
        this.opcionSino = opcionSino;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_compras", nullable=false)
    public Compras getCompras() {
        return this.compras;
    }
    
    public void setCompras(Compras compras) {
        this.compras = compras;
    }
    
    @Column(name="codigo_tipo_producto", nullable=false, length=64)
    public String getCodigoTipoProducto() {
        return this.codigoTipoProducto;
    }
    
    public void setCodigoTipoProducto(String codigoTipoProducto) {
        this.codigoTipoProducto = codigoTipoProducto;
    }
    
    @Column(name="nombre_tipo_producto", nullable=false)
    public String getNombreTipoProducto() {
        return this.nombreTipoProducto;
    }
    
    public void setNombreTipoProducto(String nombreTipoProducto) {
        this.nombreTipoProducto = nombreTipoProducto;
    }
    
    @Column(name="lote", length=32)
    public String getLote() {
        return this.lote;
    }
    
    public void setLote(String lote) {
        this.lote = lote;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_expedicion", length=29)
    public Date getFechaExpedicion() {
        return this.fechaExpedicion;
    }
    
    public void setFechaExpedicion(Date fechaExpedicion) {
        this.fechaExpedicion = fechaExpedicion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_vencimiento", length=29)
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    
    @Column(name="descripcion_renglon_compras")
    public String getDescripcionRenglonCompras() {
        return this.descripcionRenglonCompras;
    }
    
    public void setDescripcionRenglonCompras(String descripcionRenglonCompras) {
        this.descripcionRenglonCompras = descripcionRenglonCompras;
    }
    
    @Column(name="porcentaje_iva", nullable=false, precision=8, scale=8)
    public float getPorcentajeIva() {
        return this.porcentajeIva;
    }
    
    public void setPorcentajeIva(float porcentajeIva) {
        this.porcentajeIva = porcentajeIva;
    }
    
    @Column(name="cantidad_renglon_compras", nullable=false, precision=17, scale=17)
    public double getCantidadRenglonCompras() {
        return this.cantidadRenglonCompras;
    }
    
    public void setCantidadRenglonCompras(double cantidadRenglonCompras) {
        this.cantidadRenglonCompras = cantidadRenglonCompras;
    }
    
    @Column(name="precio_tipo_producto", nullable=false, precision=22)
    public BigDecimal getPrecioTipoProducto() {
        return this.precioTipoProducto;
    }
    
    public void setPrecioTipoProducto(BigDecimal precioTipoProducto) {
        this.precioTipoProducto = precioTipoProducto;
    }
    
    @Column(name="total_renglon_compras", nullable=false, precision=22)
    public BigDecimal getTotalRenglonCompras() {
        return this.totalRenglonCompras;
    }
    
    public void setTotalRenglonCompras(BigDecimal totalRenglonCompras) {
        this.totalRenglonCompras = totalRenglonCompras;
    }
    
    @Column(name="usuario_creacion", length=64)
    public String getUsuarioCreacion() {
        return this.usuarioCreacion;
    }
    
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_creacion", length=29)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    
    @Column(name="usuario_modificacion", length=64)
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modificacion", length=29)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    /**
     * toString
     * @return String
     */
     @Override
     public String toString() {
	  StringBuilder buffer = new StringBuilder();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("id").append("='").append(getId()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("opcionSino").append("='").append(getOpcionSino()).append("' ");			
      buffer.append("compras").append("='").append(getCompras()).append("' ");			
      buffer.append("codigoTipoProducto").append("='").append(getCodigoTipoProducto()).append("' ");			
      buffer.append("nombreTipoProducto").append("='").append(getNombreTipoProducto()).append("' ");			
      buffer.append("lote").append("='").append(getLote()).append("' ");			
      buffer.append("fechaExpedicion").append("='").append(getFechaExpedicion()).append("' ");			
      buffer.append("fechaVencimiento").append("='").append(getFechaVencimiento()).append("' ");			
      buffer.append("descripcionRenglonCompras").append("='").append(getDescripcionRenglonCompras()).append("' ");			
      buffer.append("porcentajeIva").append("='").append(getPorcentajeIva()).append("' ");			
      buffer.append("cantidadRenglonCompras").append("='").append(getCantidadRenglonCompras()).append("' ");			
      buffer.append("precioTipoProducto").append("='").append(getPrecioTipoProducto()).append("' ");			
      buffer.append("totalRenglonCompras").append("='").append(getTotalRenglonCompras()).append("' ");			
      buffer.append("usuarioCreacion").append("='").append(getUsuarioCreacion()).append("' ");			
      buffer.append("fechaCreacion").append("='").append(getFechaCreacion()).append("' ");			
      buffer.append("usuarioModificacion").append("='").append(getUsuarioModificacion()).append("' ");			
      buffer.append("fechaModificacion").append("='").append(getFechaModificacion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }

	@Override
	public boolean equals(Object other) {
         if (this == other) 
         	return true;
         	
		 if (other == null) 
		 	return false;
		 	
		 if (!(other instanceof RenglonCompras)) 
		 	return false;
		 	
		 RenglonCompras castOther = ( RenglonCompras ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && (this.getVersion()==castOther.getVersion());
   }
   
   @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + (int) this.getVersion();
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         return result;
   }   

  // The following is extra code specified in src/main/config/templates
// Adding extra-code
	private boolean comesFromExternalDataSource = false;
	private boolean selected;
	
	@javax.persistence.Transient
    public boolean isExternalDataSource() {
		return this.comesFromExternalDataSource;
    }

    public void setExternalDataSource(boolean value) {
        this.comesFromExternalDataSource = value;
    }

	@javax.persistence.Transient
	public boolean getSelected() {
		return selected;
	}

    public void setSelected(boolean selected) {
		this.selected = selected;
    }
    
    public void cleanPOJO() {
		if(this.opcionSino != null &&
			(opcionSino.getId() == null || this.opcionSino.getId().longValue() == 0)) {
			opcionSino = null;
		}
		if(this.compras != null &&
			(compras.getId() == null || this.compras.getId().longValue() == 0)) {
			compras = null;
		}
    }
    
    public void fillPOJO() {
		if(this.opcionSino == null) {
			opcionSino = new OpcionSino();
		}
		if(this.compras == null) {
			compras = new Compras();
		}
    }
    
    public RenglonCompras createPOJO() {
		fillPOJO();
		
		return this;
	}
	
//	@PrePersist
//	public void onPrePersist() {
//		this.fechaCreacion = new Date();
//		this.usuarioCreacion = getSecurityContextPrincipal();
//	}
//
//	@PreUpdate
//	public void onPreUpdate() {
//		this.fechaModificacion = new Date();
//		this.usuarioModificacion = getSecurityContextPrincipal();
//	}
//
//	@javax.persistence.Transient
//	private String getSecurityContextPrincipal() {
//		String principal;
//		String UNKNOWN_USER = "unknownUser";
//
//		if (SecurityContextHolder.getContext().getAuthentication() == null) {
//			principal = UNKNOWN_USER;
//		} else {
//			try {
//				principal = ((User) SecurityContextHolder.getContext().getAuthentication().getPrincipal())
//						.getUsername();
//			} catch (ClassCastException e) {
//				principal = UNKNOWN_USER;
//			}
//		}
//
//		return principal;
//	}
	
  // end of extra code specified in the hbm.xml files

}

