package com.gvt.main.hibernate.model;
// Generated 09-feb-2020 20:04:15 by Hibernate Tools 3.2.2.GA and Assent Architecture


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.gvt.core.domain.types.Auditable;
import com.gvt.core.domain.types.Cleanable;
import com.gvt.core.domain.types.Fillable;
import com.gvt.core.domain.types.Identificable;
import com.gvt.core.domain.types.Seleccionable;
import com.gvt.core.domain.types.Versionable;
import java.sql.Timestamp;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlTransient;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * TiempoEstimadoAtencion generated by hbm2java
 */
@Entity
@EntityListeners({ AuditingEntityListener.class })
@Table(name="tiempo_estimado_atencion"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames={"id_persona", "id_motivo_calendario"}) 
)
public class TiempoEstimadoAtencion  implements Versionable,Seleccionable,Identificable,Fillable,Cleanable,Auditable,java.io.Serializable {


 	
 	private Long id;
 	
 	private long version;
 	
 	private MotivoCalendario motivoCalendario;
 	
 	private Persona persona;
 	
 	private int tiempoEstimadoAtencion;
 	
 	private Integer numeroMaxLunes;
 	
 	private Integer numeroMaxMartes;
 	
 	private Integer numeroMaxMiercoles;
 	
 	private Integer numeroMaxJueves;
 	
 	private Integer numeroMaxViernes;
 	
 	private Integer numeroMaxSabado;
 	
 	private Integer numeroMaxDomingo;
 	@CreatedBy
 	private String usuarioCreacion;
 	@CreatedDate
 	private Date fechaCreacion;
 	@LastModifiedBy
 	private String usuarioModificacion;
 	@LastModifiedDate
 	private Date fechaModificacion;

    public TiempoEstimadoAtencion() {
    	// default constructor
    }

	
    public TiempoEstimadoAtencion(MotivoCalendario motivoCalendario, Persona persona, int tiempoEstimadoAtencion) {
        this.motivoCalendario = motivoCalendario;
        this.persona = persona;
        this.tiempoEstimadoAtencion = tiempoEstimadoAtencion;
    }
    public TiempoEstimadoAtencion(MotivoCalendario motivoCalendario, Persona persona, int tiempoEstimadoAtencion, Integer numeroMaxLunes, Integer numeroMaxMartes, Integer numeroMaxMiercoles, Integer numeroMaxJueves, Integer numeroMaxViernes, Integer numeroMaxSabado, Integer numeroMaxDomingo, String usuarioCreacion, Date fechaCreacion, String usuarioModificacion, Date fechaModificacion) {
       this.motivoCalendario = motivoCalendario;
       this.persona = persona;
       this.tiempoEstimadoAtencion = tiempoEstimadoAtencion;
       this.numeroMaxLunes = numeroMaxLunes;
       this.numeroMaxMartes = numeroMaxMartes;
       this.numeroMaxMiercoles = numeroMaxMiercoles;
       this.numeroMaxJueves = numeroMaxJueves;
       this.numeroMaxViernes = numeroMaxViernes;
       this.numeroMaxSabado = numeroMaxSabado;
       this.numeroMaxDomingo = numeroMaxDomingo;
       this.usuarioCreacion = usuarioCreacion;
       this.fechaCreacion = fechaCreacion;
       this.usuarioModificacion = usuarioModificacion;
       this.fechaModificacion = fechaModificacion;
    }
   
  @GenericGenerator(name = "tiempo_estimado_atencion_seq_gen", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator",
            parameters = {
                    @Parameter(name = "sequence_name", value = "tiempo_estimado_atencion_id_seq"),
                    @Parameter(name = "initial_value", value = "1"),
                    @Parameter(name = "increment_size", value = "1")
            })
  @GeneratedValue(generator = "tiempo_estimado_atencion_seq_gen")
  @Id
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    @Version
    @Column(name="version", nullable=false)
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_motivo_calendario", nullable=false)
    public MotivoCalendario getMotivoCalendario() {
        return this.motivoCalendario;
    }
    
    public void setMotivoCalendario(MotivoCalendario motivoCalendario) {
        this.motivoCalendario = motivoCalendario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_persona", nullable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    
    @Column(name="tiempo_estimado_atencion", nullable=false)
    public int getTiempoEstimadoAtencion() {
        return this.tiempoEstimadoAtencion;
    }
    
    public void setTiempoEstimadoAtencion(int tiempoEstimadoAtencion) {
        this.tiempoEstimadoAtencion = tiempoEstimadoAtencion;
    }
    
    @Column(name="numero_max_lunes")
    public Integer getNumeroMaxLunes() {
        return this.numeroMaxLunes;
    }
    
    public void setNumeroMaxLunes(Integer numeroMaxLunes) {
        this.numeroMaxLunes = numeroMaxLunes;
    }
    
    @Column(name="numero_max_martes")
    public Integer getNumeroMaxMartes() {
        return this.numeroMaxMartes;
    }
    
    public void setNumeroMaxMartes(Integer numeroMaxMartes) {
        this.numeroMaxMartes = numeroMaxMartes;
    }
    
    @Column(name="numero_max_miercoles")
    public Integer getNumeroMaxMiercoles() {
        return this.numeroMaxMiercoles;
    }
    
    public void setNumeroMaxMiercoles(Integer numeroMaxMiercoles) {
        this.numeroMaxMiercoles = numeroMaxMiercoles;
    }
    
    @Column(name="numero_max_jueves")
    public Integer getNumeroMaxJueves() {
        return this.numeroMaxJueves;
    }
    
    public void setNumeroMaxJueves(Integer numeroMaxJueves) {
        this.numeroMaxJueves = numeroMaxJueves;
    }
    
    @Column(name="numero_max_viernes")
    public Integer getNumeroMaxViernes() {
        return this.numeroMaxViernes;
    }
    
    public void setNumeroMaxViernes(Integer numeroMaxViernes) {
        this.numeroMaxViernes = numeroMaxViernes;
    }
    
    @Column(name="numero_max_sabado")
    public Integer getNumeroMaxSabado() {
        return this.numeroMaxSabado;
    }
    
    public void setNumeroMaxSabado(Integer numeroMaxSabado) {
        this.numeroMaxSabado = numeroMaxSabado;
    }
    
    @Column(name="numero_max_domingo")
    public Integer getNumeroMaxDomingo() {
        return this.numeroMaxDomingo;
    }
    
    public void setNumeroMaxDomingo(Integer numeroMaxDomingo) {
        this.numeroMaxDomingo = numeroMaxDomingo;
    }
    
    @Column(name="usuario_creacion", length=64)
    public String getUsuarioCreacion() {
        return this.usuarioCreacion;
    }
    
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_creacion", length=29)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    
    @Column(name="usuario_modificacion", length=64)
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modificacion", length=29)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    /**
     * toString
     * @return String
     */
     @Override
     public String toString() {
	  StringBuilder buffer = new StringBuilder();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("id").append("='").append(getId()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("motivoCalendario").append("='").append(getMotivoCalendario()).append("' ");			
      buffer.append("persona").append("='").append(getPersona()).append("' ");			
      buffer.append("tiempoEstimadoAtencion").append("='").append(getTiempoEstimadoAtencion()).append("' ");			
      buffer.append("numeroMaxLunes").append("='").append(getNumeroMaxLunes()).append("' ");			
      buffer.append("numeroMaxMartes").append("='").append(getNumeroMaxMartes()).append("' ");			
      buffer.append("numeroMaxMiercoles").append("='").append(getNumeroMaxMiercoles()).append("' ");			
      buffer.append("numeroMaxJueves").append("='").append(getNumeroMaxJueves()).append("' ");			
      buffer.append("numeroMaxViernes").append("='").append(getNumeroMaxViernes()).append("' ");			
      buffer.append("numeroMaxSabado").append("='").append(getNumeroMaxSabado()).append("' ");			
      buffer.append("numeroMaxDomingo").append("='").append(getNumeroMaxDomingo()).append("' ");			
      buffer.append("usuarioCreacion").append("='").append(getUsuarioCreacion()).append("' ");			
      buffer.append("fechaCreacion").append("='").append(getFechaCreacion()).append("' ");			
      buffer.append("usuarioModificacion").append("='").append(getUsuarioModificacion()).append("' ");			
      buffer.append("fechaModificacion").append("='").append(getFechaModificacion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }

	@Override
	public boolean equals(Object other) {
         if (this == other) 
         	return true;
         	
		 if (other == null) 
		 	return false;
		 	
		 if (!(other instanceof TiempoEstimadoAtencion)) 
		 	return false;
		 	
		 TiempoEstimadoAtencion castOther = ( TiempoEstimadoAtencion ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && (this.getVersion()==castOther.getVersion());
   }
   
   @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + (int) this.getVersion();
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         return result;
   }   

  // The following is extra code specified in src/main/config/templates
// Adding extra-code
	private boolean comesFromExternalDataSource = false;
	private boolean selected;
	
	@javax.persistence.Transient
    public boolean isExternalDataSource() {
		return this.comesFromExternalDataSource;
    }

    public void setExternalDataSource(boolean value) {
        this.comesFromExternalDataSource = value;
    }

	@javax.persistence.Transient
	public boolean getSelected() {
		return selected;
	}

    public void setSelected(boolean selected) {
		this.selected = selected;
    }
    
    public void cleanPOJO() {
		if(this.motivoCalendario != null &&
			(motivoCalendario.getId() == null || this.motivoCalendario.getId().longValue() == 0)) {
			motivoCalendario = null;
		}
		if(this.persona != null &&
			(persona.getId() == null || this.persona.getId().longValue() == 0)) {
			persona = null;
		}
    }
    
    public void fillPOJO() {
		if(this.motivoCalendario == null) {
			motivoCalendario = new MotivoCalendario();
		}
		if(this.persona == null) {
			persona = new Persona();
		}
    }
    
    public TiempoEstimadoAtencion createPOJO() {
		fillPOJO();
		
		return this;
	}
	
//	@PrePersist
//	public void onPrePersist() {
//		this.fechaCreacion = new Date();
//		this.usuarioCreacion = getSecurityContextPrincipal();
//	}
//
//	@PreUpdate
//	public void onPreUpdate() {
//		this.fechaModificacion = new Date();
//		this.usuarioModificacion = getSecurityContextPrincipal();
//	}
//
//	@javax.persistence.Transient
//	private String getSecurityContextPrincipal() {
//		String principal;
//		String UNKNOWN_USER = "unknownUser";
//
//		if (SecurityContextHolder.getContext().getAuthentication() == null) {
//			principal = UNKNOWN_USER;
//		} else {
//			try {
//				principal = ((User) SecurityContextHolder.getContext().getAuthentication().getPrincipal())
//						.getUsername();
//			} catch (ClassCastException e) {
//				principal = UNKNOWN_USER;
//			}
//		}
//
//		return principal;
//	}
	
  // end of extra code specified in the hbm.xml files

}

