package com.gvt.main.hibernate.model;
// Generated 09-feb-2020 20:04:15 by Hibernate Tools 3.2.2.GA and Assent Architecture


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.gvt.core.domain.types.Auditable;
import com.gvt.core.domain.types.Cleanable;
import com.gvt.core.domain.types.Fillable;
import com.gvt.core.domain.types.Identificable;
import com.gvt.core.domain.types.Seleccionable;
import com.gvt.core.domain.types.Versionable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlTransient;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * TipoProductoOrganizacion generated by hbm2java
 */
@Entity
@EntityListeners({ AuditingEntityListener.class })
@Table(name="tipo_producto_organizacion"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames={"id_tipo_producto", "id_organizacion"}) 
)
public class TipoProductoOrganizacion  implements Versionable,Seleccionable,Identificable,Fillable,Cleanable,Auditable,java.io.Serializable {


 	
 	private Long id;
 	
 	private long version;
 	
 	private OpcionSino opcionSino;
 	
 	private TipoProducto tipoProducto;
 	
 	private Organizacion organizacion;
 	
 	private BigDecimal precioTipoProducto;
 	
 	private BigDecimal precioTipoProducto1;
 	
 	private BigDecimal precioTipoProducto2;
 	
 	private BigDecimal precioTipoProducto3;
 	
 	private BigDecimal precioTipoProducto4;
 	
 	private BigDecimal precioTipoProducto5;
 	
 	private BigDecimal precioTipoProducto6;
 	
 	private BigDecimal precioTipoProducto7;
 	
 	private BigDecimal precioTipoProducto8;
 	
 	private BigDecimal precioTipoProducto9;
 	
 	private double utilidadTipoProducto;
 	
 	private Double utilidadTipoProducto1;
 	
 	private Double utilidadTipoProducto2;
 	
 	private Double utilidadTipoProducto3;
 	
 	private Double utilidadTipoProducto4;
 	
 	private Double utilidadTipoProducto5;
 	
 	private Double utilidadTipoProducto6;
 	
 	private Double utilidadTipoProducto7;
 	
 	private Double utilidadTipoProducto8;
 	
 	private Double utilidadTipoProducto9;
 	
 	private Float porcentajeComision;
 	
 	private Float porcentajeComision1;
 	
 	private Float porcentajeComision2;
 	
 	private Float porcentajeComision3;
 	
 	private Float porcentajeComision4;
 	
 	private Float porcentajeComision5;
 	
 	private Float porcentajeComision6;
 	
 	private Float porcentajeComision7;
 	
 	private Float porcentajeComision8;
 	
 	private Float porcentajeComision9;
 	
 	private BigDecimal cantidadMinimaStock;
 	
 	private BigDecimal cantidadMaximaStock;
 	@CreatedBy
 	private String usuarioCreacion;
 	@CreatedDate
 	private Date fechaCreacion;
 	@LastModifiedBy
 	private String usuarioModificacion;
 	@LastModifiedDate
 	private Date fechaModificacion;

    public TipoProductoOrganizacion() {
    	// default constructor
    }

	
    public TipoProductoOrganizacion(OpcionSino opcionSino, TipoProducto tipoProducto, Organizacion organizacion, BigDecimal precioTipoProducto, double utilidadTipoProducto, BigDecimal cantidadMinimaStock, BigDecimal cantidadMaximaStock) {
        this.opcionSino = opcionSino;
        this.tipoProducto = tipoProducto;
        this.organizacion = organizacion;
        this.precioTipoProducto = precioTipoProducto;
        this.utilidadTipoProducto = utilidadTipoProducto;
        this.cantidadMinimaStock = cantidadMinimaStock;
        this.cantidadMaximaStock = cantidadMaximaStock;
    }
    public TipoProductoOrganizacion(OpcionSino opcionSino, TipoProducto tipoProducto, Organizacion organizacion, BigDecimal precioTipoProducto, BigDecimal precioTipoProducto1, BigDecimal precioTipoProducto2, BigDecimal precioTipoProducto3, BigDecimal precioTipoProducto4, BigDecimal precioTipoProducto5, BigDecimal precioTipoProducto6, BigDecimal precioTipoProducto7, BigDecimal precioTipoProducto8, BigDecimal precioTipoProducto9, double utilidadTipoProducto, Double utilidadTipoProducto1, Double utilidadTipoProducto2, Double utilidadTipoProducto3, Double utilidadTipoProducto4, Double utilidadTipoProducto5, Double utilidadTipoProducto6, Double utilidadTipoProducto7, Double utilidadTipoProducto8, Double utilidadTipoProducto9, Float porcentajeComision, Float porcentajeComision1, Float porcentajeComision2, Float porcentajeComision3, Float porcentajeComision4, Float porcentajeComision5, Float porcentajeComision6, Float porcentajeComision7, Float porcentajeComision8, Float porcentajeComision9, BigDecimal cantidadMinimaStock, BigDecimal cantidadMaximaStock, String usuarioCreacion, Date fechaCreacion, String usuarioModificacion, Date fechaModificacion) {
       this.opcionSino = opcionSino;
       this.tipoProducto = tipoProducto;
       this.organizacion = organizacion;
       this.precioTipoProducto = precioTipoProducto;
       this.precioTipoProducto1 = precioTipoProducto1;
       this.precioTipoProducto2 = precioTipoProducto2;
       this.precioTipoProducto3 = precioTipoProducto3;
       this.precioTipoProducto4 = precioTipoProducto4;
       this.precioTipoProducto5 = precioTipoProducto5;
       this.precioTipoProducto6 = precioTipoProducto6;
       this.precioTipoProducto7 = precioTipoProducto7;
       this.precioTipoProducto8 = precioTipoProducto8;
       this.precioTipoProducto9 = precioTipoProducto9;
       this.utilidadTipoProducto = utilidadTipoProducto;
       this.utilidadTipoProducto1 = utilidadTipoProducto1;
       this.utilidadTipoProducto2 = utilidadTipoProducto2;
       this.utilidadTipoProducto3 = utilidadTipoProducto3;
       this.utilidadTipoProducto4 = utilidadTipoProducto4;
       this.utilidadTipoProducto5 = utilidadTipoProducto5;
       this.utilidadTipoProducto6 = utilidadTipoProducto6;
       this.utilidadTipoProducto7 = utilidadTipoProducto7;
       this.utilidadTipoProducto8 = utilidadTipoProducto8;
       this.utilidadTipoProducto9 = utilidadTipoProducto9;
       this.porcentajeComision = porcentajeComision;
       this.porcentajeComision1 = porcentajeComision1;
       this.porcentajeComision2 = porcentajeComision2;
       this.porcentajeComision3 = porcentajeComision3;
       this.porcentajeComision4 = porcentajeComision4;
       this.porcentajeComision5 = porcentajeComision5;
       this.porcentajeComision6 = porcentajeComision6;
       this.porcentajeComision7 = porcentajeComision7;
       this.porcentajeComision8 = porcentajeComision8;
       this.porcentajeComision9 = porcentajeComision9;
       this.cantidadMinimaStock = cantidadMinimaStock;
       this.cantidadMaximaStock = cantidadMaximaStock;
       this.usuarioCreacion = usuarioCreacion;
       this.fechaCreacion = fechaCreacion;
       this.usuarioModificacion = usuarioModificacion;
       this.fechaModificacion = fechaModificacion;
    }
   
  @GenericGenerator(name = "tipo_producto_organizacion_seq_gen", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator",
            parameters = {
                    @Parameter(name = "sequence_name", value = "tipo_producto_organizacion_id_seq"),
                    @Parameter(name = "initial_value", value = "1"),
                    @Parameter(name = "increment_size", value = "1")
            })
  @GeneratedValue(generator = "tipo_producto_organizacion_seq_gen")
  @Id
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    @Version
    @Column(name="version", nullable=false)
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="es_deshabilitado", nullable=false)
    public OpcionSino getOpcionSino() {
        return this.opcionSino;
    }
    
    public void setOpcionSino(OpcionSino opcionSino) {
        this.opcionSino = opcionSino;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tipo_producto", nullable=false)
    public TipoProducto getTipoProducto() {
        return this.tipoProducto;
    }
    
    public void setTipoProducto(TipoProducto tipoProducto) {
        this.tipoProducto = tipoProducto;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_organizacion", nullable=false)
    public Organizacion getOrganizacion() {
        return this.organizacion;
    }
    
    public void setOrganizacion(Organizacion organizacion) {
        this.organizacion = organizacion;
    }
    
    @Column(name="precio_tipo_producto", nullable=false, precision=22)
    public BigDecimal getPrecioTipoProducto() {
        return this.precioTipoProducto;
    }
    
    public void setPrecioTipoProducto(BigDecimal precioTipoProducto) {
        this.precioTipoProducto = precioTipoProducto;
    }
    
    @Column(name="precio_tipo_producto1", precision=22)
    public BigDecimal getPrecioTipoProducto1() {
        return this.precioTipoProducto1;
    }
    
    public void setPrecioTipoProducto1(BigDecimal precioTipoProducto1) {
        this.precioTipoProducto1 = precioTipoProducto1;
    }
    
    @Column(name="precio_tipo_producto2", precision=22)
    public BigDecimal getPrecioTipoProducto2() {
        return this.precioTipoProducto2;
    }
    
    public void setPrecioTipoProducto2(BigDecimal precioTipoProducto2) {
        this.precioTipoProducto2 = precioTipoProducto2;
    }
    
    @Column(name="precio_tipo_producto3", precision=22)
    public BigDecimal getPrecioTipoProducto3() {
        return this.precioTipoProducto3;
    }
    
    public void setPrecioTipoProducto3(BigDecimal precioTipoProducto3) {
        this.precioTipoProducto3 = precioTipoProducto3;
    }
    
    @Column(name="precio_tipo_producto4", precision=22)
    public BigDecimal getPrecioTipoProducto4() {
        return this.precioTipoProducto4;
    }
    
    public void setPrecioTipoProducto4(BigDecimal precioTipoProducto4) {
        this.precioTipoProducto4 = precioTipoProducto4;
    }
    
    @Column(name="precio_tipo_producto5", precision=22)
    public BigDecimal getPrecioTipoProducto5() {
        return this.precioTipoProducto5;
    }
    
    public void setPrecioTipoProducto5(BigDecimal precioTipoProducto5) {
        this.precioTipoProducto5 = precioTipoProducto5;
    }
    
    @Column(name="precio_tipo_producto6", precision=22)
    public BigDecimal getPrecioTipoProducto6() {
        return this.precioTipoProducto6;
    }
    
    public void setPrecioTipoProducto6(BigDecimal precioTipoProducto6) {
        this.precioTipoProducto6 = precioTipoProducto6;
    }
    
    @Column(name="precio_tipo_producto7", precision=22)
    public BigDecimal getPrecioTipoProducto7() {
        return this.precioTipoProducto7;
    }
    
    public void setPrecioTipoProducto7(BigDecimal precioTipoProducto7) {
        this.precioTipoProducto7 = precioTipoProducto7;
    }
    
    @Column(name="precio_tipo_producto8", precision=22)
    public BigDecimal getPrecioTipoProducto8() {
        return this.precioTipoProducto8;
    }
    
    public void setPrecioTipoProducto8(BigDecimal precioTipoProducto8) {
        this.precioTipoProducto8 = precioTipoProducto8;
    }
    
    @Column(name="precio_tipo_producto9", precision=22)
    public BigDecimal getPrecioTipoProducto9() {
        return this.precioTipoProducto9;
    }
    
    public void setPrecioTipoProducto9(BigDecimal precioTipoProducto9) {
        this.precioTipoProducto9 = precioTipoProducto9;
    }
    
    @Column(name="utilidad_tipo_producto", nullable=false, precision=17, scale=17)
    public double getUtilidadTipoProducto() {
        return this.utilidadTipoProducto;
    }
    
    public void setUtilidadTipoProducto(double utilidadTipoProducto) {
        this.utilidadTipoProducto = utilidadTipoProducto;
    }
    
    @Column(name="utilidad_tipo_producto1", precision=17, scale=17)
    public Double getUtilidadTipoProducto1() {
        return this.utilidadTipoProducto1;
    }
    
    public void setUtilidadTipoProducto1(Double utilidadTipoProducto1) {
        this.utilidadTipoProducto1 = utilidadTipoProducto1;
    }
    
    @Column(name="utilidad_tipo_producto2", precision=17, scale=17)
    public Double getUtilidadTipoProducto2() {
        return this.utilidadTipoProducto2;
    }
    
    public void setUtilidadTipoProducto2(Double utilidadTipoProducto2) {
        this.utilidadTipoProducto2 = utilidadTipoProducto2;
    }
    
    @Column(name="utilidad_tipo_producto3", precision=17, scale=17)
    public Double getUtilidadTipoProducto3() {
        return this.utilidadTipoProducto3;
    }
    
    public void setUtilidadTipoProducto3(Double utilidadTipoProducto3) {
        this.utilidadTipoProducto3 = utilidadTipoProducto3;
    }
    
    @Column(name="utilidad_tipo_producto4", precision=17, scale=17)
    public Double getUtilidadTipoProducto4() {
        return this.utilidadTipoProducto4;
    }
    
    public void setUtilidadTipoProducto4(Double utilidadTipoProducto4) {
        this.utilidadTipoProducto4 = utilidadTipoProducto4;
    }
    
    @Column(name="utilidad_tipo_producto5", precision=17, scale=17)
    public Double getUtilidadTipoProducto5() {
        return this.utilidadTipoProducto5;
    }
    
    public void setUtilidadTipoProducto5(Double utilidadTipoProducto5) {
        this.utilidadTipoProducto5 = utilidadTipoProducto5;
    }
    
    @Column(name="utilidad_tipo_producto6", precision=17, scale=17)
    public Double getUtilidadTipoProducto6() {
        return this.utilidadTipoProducto6;
    }
    
    public void setUtilidadTipoProducto6(Double utilidadTipoProducto6) {
        this.utilidadTipoProducto6 = utilidadTipoProducto6;
    }
    
    @Column(name="utilidad_tipo_producto7", precision=17, scale=17)
    public Double getUtilidadTipoProducto7() {
        return this.utilidadTipoProducto7;
    }
    
    public void setUtilidadTipoProducto7(Double utilidadTipoProducto7) {
        this.utilidadTipoProducto7 = utilidadTipoProducto7;
    }
    
    @Column(name="utilidad_tipo_producto8", precision=17, scale=17)
    public Double getUtilidadTipoProducto8() {
        return this.utilidadTipoProducto8;
    }
    
    public void setUtilidadTipoProducto8(Double utilidadTipoProducto8) {
        this.utilidadTipoProducto8 = utilidadTipoProducto8;
    }
    
    @Column(name="utilidad_tipo_producto9", precision=17, scale=17)
    public Double getUtilidadTipoProducto9() {
        return this.utilidadTipoProducto9;
    }
    
    public void setUtilidadTipoProducto9(Double utilidadTipoProducto9) {
        this.utilidadTipoProducto9 = utilidadTipoProducto9;
    }
    
    @Column(name="porcentaje_comision", precision=8, scale=8)
    public Float getPorcentajeComision() {
        return this.porcentajeComision;
    }
    
    public void setPorcentajeComision(Float porcentajeComision) {
        this.porcentajeComision = porcentajeComision;
    }
    
    @Column(name="porcentaje_comision1", precision=8, scale=8)
    public Float getPorcentajeComision1() {
        return this.porcentajeComision1;
    }
    
    public void setPorcentajeComision1(Float porcentajeComision1) {
        this.porcentajeComision1 = porcentajeComision1;
    }
    
    @Column(name="porcentaje_comision2", precision=8, scale=8)
    public Float getPorcentajeComision2() {
        return this.porcentajeComision2;
    }
    
    public void setPorcentajeComision2(Float porcentajeComision2) {
        this.porcentajeComision2 = porcentajeComision2;
    }
    
    @Column(name="porcentaje_comision3", precision=8, scale=8)
    public Float getPorcentajeComision3() {
        return this.porcentajeComision3;
    }
    
    public void setPorcentajeComision3(Float porcentajeComision3) {
        this.porcentajeComision3 = porcentajeComision3;
    }
    
    @Column(name="porcentaje_comision4", precision=8, scale=8)
    public Float getPorcentajeComision4() {
        return this.porcentajeComision4;
    }
    
    public void setPorcentajeComision4(Float porcentajeComision4) {
        this.porcentajeComision4 = porcentajeComision4;
    }
    
    @Column(name="porcentaje_comision5", precision=8, scale=8)
    public Float getPorcentajeComision5() {
        return this.porcentajeComision5;
    }
    
    public void setPorcentajeComision5(Float porcentajeComision5) {
        this.porcentajeComision5 = porcentajeComision5;
    }
    
    @Column(name="porcentaje_comision6", precision=8, scale=8)
    public Float getPorcentajeComision6() {
        return this.porcentajeComision6;
    }
    
    public void setPorcentajeComision6(Float porcentajeComision6) {
        this.porcentajeComision6 = porcentajeComision6;
    }
    
    @Column(name="porcentaje_comision7", precision=8, scale=8)
    public Float getPorcentajeComision7() {
        return this.porcentajeComision7;
    }
    
    public void setPorcentajeComision7(Float porcentajeComision7) {
        this.porcentajeComision7 = porcentajeComision7;
    }
    
    @Column(name="porcentaje_comision8", precision=8, scale=8)
    public Float getPorcentajeComision8() {
        return this.porcentajeComision8;
    }
    
    public void setPorcentajeComision8(Float porcentajeComision8) {
        this.porcentajeComision8 = porcentajeComision8;
    }
    
    @Column(name="porcentaje_comision9", precision=8, scale=8)
    public Float getPorcentajeComision9() {
        return this.porcentajeComision9;
    }
    
    public void setPorcentajeComision9(Float porcentajeComision9) {
        this.porcentajeComision9 = porcentajeComision9;
    }
    
    @Column(name="cantidad_minima_stock", nullable=false, precision=22)
    public BigDecimal getCantidadMinimaStock() {
        return this.cantidadMinimaStock;
    }
    
    public void setCantidadMinimaStock(BigDecimal cantidadMinimaStock) {
        this.cantidadMinimaStock = cantidadMinimaStock;
    }
    
    @Column(name="cantidad_maxima_stock", nullable=false, precision=22)
    public BigDecimal getCantidadMaximaStock() {
        return this.cantidadMaximaStock;
    }
    
    public void setCantidadMaximaStock(BigDecimal cantidadMaximaStock) {
        this.cantidadMaximaStock = cantidadMaximaStock;
    }
    
    @Column(name="usuario_creacion", length=64)
    public String getUsuarioCreacion() {
        return this.usuarioCreacion;
    }
    
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_creacion", length=29)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    
    @Column(name="usuario_modificacion", length=64)
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modificacion", length=29)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    /**
     * toString
     * @return String
     */
     @Override
     public String toString() {
	  StringBuilder buffer = new StringBuilder();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("id").append("='").append(getId()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("opcionSino").append("='").append(getOpcionSino()).append("' ");			
      buffer.append("tipoProducto").append("='").append(getTipoProducto()).append("' ");			
      buffer.append("organizacion").append("='").append(getOrganizacion()).append("' ");			
      buffer.append("precioTipoProducto").append("='").append(getPrecioTipoProducto()).append("' ");			
      buffer.append("precioTipoProducto1").append("='").append(getPrecioTipoProducto1()).append("' ");			
      buffer.append("precioTipoProducto2").append("='").append(getPrecioTipoProducto2()).append("' ");			
      buffer.append("precioTipoProducto3").append("='").append(getPrecioTipoProducto3()).append("' ");			
      buffer.append("precioTipoProducto4").append("='").append(getPrecioTipoProducto4()).append("' ");			
      buffer.append("precioTipoProducto5").append("='").append(getPrecioTipoProducto5()).append("' ");			
      buffer.append("precioTipoProducto6").append("='").append(getPrecioTipoProducto6()).append("' ");			
      buffer.append("precioTipoProducto7").append("='").append(getPrecioTipoProducto7()).append("' ");			
      buffer.append("precioTipoProducto8").append("='").append(getPrecioTipoProducto8()).append("' ");			
      buffer.append("precioTipoProducto9").append("='").append(getPrecioTipoProducto9()).append("' ");			
      buffer.append("utilidadTipoProducto").append("='").append(getUtilidadTipoProducto()).append("' ");			
      buffer.append("utilidadTipoProducto1").append("='").append(getUtilidadTipoProducto1()).append("' ");			
      buffer.append("utilidadTipoProducto2").append("='").append(getUtilidadTipoProducto2()).append("' ");			
      buffer.append("utilidadTipoProducto3").append("='").append(getUtilidadTipoProducto3()).append("' ");			
      buffer.append("utilidadTipoProducto4").append("='").append(getUtilidadTipoProducto4()).append("' ");			
      buffer.append("utilidadTipoProducto5").append("='").append(getUtilidadTipoProducto5()).append("' ");			
      buffer.append("utilidadTipoProducto6").append("='").append(getUtilidadTipoProducto6()).append("' ");			
      buffer.append("utilidadTipoProducto7").append("='").append(getUtilidadTipoProducto7()).append("' ");			
      buffer.append("utilidadTipoProducto8").append("='").append(getUtilidadTipoProducto8()).append("' ");			
      buffer.append("utilidadTipoProducto9").append("='").append(getUtilidadTipoProducto9()).append("' ");			
      buffer.append("porcentajeComision").append("='").append(getPorcentajeComision()).append("' ");			
      buffer.append("porcentajeComision1").append("='").append(getPorcentajeComision1()).append("' ");			
      buffer.append("porcentajeComision2").append("='").append(getPorcentajeComision2()).append("' ");			
      buffer.append("porcentajeComision3").append("='").append(getPorcentajeComision3()).append("' ");			
      buffer.append("porcentajeComision4").append("='").append(getPorcentajeComision4()).append("' ");			
      buffer.append("porcentajeComision5").append("='").append(getPorcentajeComision5()).append("' ");			
      buffer.append("porcentajeComision6").append("='").append(getPorcentajeComision6()).append("' ");			
      buffer.append("porcentajeComision7").append("='").append(getPorcentajeComision7()).append("' ");			
      buffer.append("porcentajeComision8").append("='").append(getPorcentajeComision8()).append("' ");			
      buffer.append("porcentajeComision9").append("='").append(getPorcentajeComision9()).append("' ");			
      buffer.append("cantidadMinimaStock").append("='").append(getCantidadMinimaStock()).append("' ");			
      buffer.append("cantidadMaximaStock").append("='").append(getCantidadMaximaStock()).append("' ");			
      buffer.append("usuarioCreacion").append("='").append(getUsuarioCreacion()).append("' ");			
      buffer.append("fechaCreacion").append("='").append(getFechaCreacion()).append("' ");			
      buffer.append("usuarioModificacion").append("='").append(getUsuarioModificacion()).append("' ");			
      buffer.append("fechaModificacion").append("='").append(getFechaModificacion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }

	@Override
	public boolean equals(Object other) {
         if (this == other) 
         	return true;
         	
		 if (other == null) 
		 	return false;
		 	
		 if (!(other instanceof TipoProductoOrganizacion)) 
		 	return false;
		 	
		 TipoProductoOrganizacion castOther = ( TipoProductoOrganizacion ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && (this.getVersion()==castOther.getVersion());
   }
   
   @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + (int) this.getVersion();
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         return result;
   }   

  // The following is extra code specified in src/main/config/templates
// Adding extra-code
	private boolean comesFromExternalDataSource = false;
	private boolean selected;
	
	@javax.persistence.Transient
    public boolean isExternalDataSource() {
		return this.comesFromExternalDataSource;
    }

    public void setExternalDataSource(boolean value) {
        this.comesFromExternalDataSource = value;
    }

	@javax.persistence.Transient
	public boolean getSelected() {
		return selected;
	}

    public void setSelected(boolean selected) {
		this.selected = selected;
    }
    
    public void cleanPOJO() {
		if(this.opcionSino != null &&
			(opcionSino.getId() == null || this.opcionSino.getId().longValue() == 0)) {
			opcionSino = null;
		}
		if(this.tipoProducto != null &&
			(tipoProducto.getId() == null || this.tipoProducto.getId().longValue() == 0)) {
			tipoProducto = null;
		}
		if(this.organizacion != null &&
			(organizacion.getId() == null || this.organizacion.getId().longValue() == 0)) {
			organizacion = null;
		}
    }
    
    public void fillPOJO() {
		if(this.opcionSino == null) {
			opcionSino = new OpcionSino();
		}
		if(this.tipoProducto == null) {
			tipoProducto = new TipoProducto();
		}
		if(this.organizacion == null) {
			organizacion = new Organizacion();
		}
    }
    
    public TipoProductoOrganizacion createPOJO() {
		fillPOJO();
		
		return this;
	}
	
//	@PrePersist
//	public void onPrePersist() {
//		this.fechaCreacion = new Date();
//		this.usuarioCreacion = getSecurityContextPrincipal();
//	}
//
//	@PreUpdate
//	public void onPreUpdate() {
//		this.fechaModificacion = new Date();
//		this.usuarioModificacion = getSecurityContextPrincipal();
//	}
//
//	@javax.persistence.Transient
//	private String getSecurityContextPrincipal() {
//		String principal;
//		String UNKNOWN_USER = "unknownUser";
//
//		if (SecurityContextHolder.getContext().getAuthentication() == null) {
//			principal = UNKNOWN_USER;
//		} else {
//			try {
//				principal = ((User) SecurityContextHolder.getContext().getAuthentication().getPrincipal())
//						.getUsername();
//			} catch (ClassCastException e) {
//				principal = UNKNOWN_USER;
//			}
//		}
//
//		return principal;
//	}
	
  // end of extra code specified in the hbm.xml files

}

