package com.gvt.main.hibernate.model;
// Generated 24-may-2020 17:36:56 by Hibernate Tools 3.2.2.GA and Assent Architecture


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.gvt.core.domain.types.Auditable;
import com.gvt.core.domain.types.Cleanable;
import com.gvt.core.domain.types.Fillable;
import com.gvt.core.domain.types.Identificable;
import com.gvt.core.domain.types.Seleccionable;
import com.gvt.core.domain.types.Versionable;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlTransient;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * TipoProductoAlmacen generated by hbm2java
 */
@Entity
@EntityListeners({ AuditingEntityListener.class })
@Table(name="tipo_producto_almacen"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames={"lote", "id_tipo_producto", "id_almacen"}) 
)
public class TipoProductoAlmacen  implements Versionable,Seleccionable,Identificable,Fillable,Cleanable,Auditable,java.io.Serializable {


 	
 	private Long id;
 	
 	private long version;
 	
 	private OpcionSino opcionSino;
 	
 	private TipoProducto tipoProducto;
 	
 	private Almacen almacen;
 	
 	private String lote;
 	
 	private double cantidadDisponibleActual;
 	
 	private double cantidadBloqueada;
 	
 	private LocalDateTime fechaExpedicion;
 	
 	private LocalDateTime fechaVencimiento;
 	@CreatedBy
 	private String usuarioCreacion;
 	@CreatedDate
 	private LocalDateTime fechaCreacion;
 	@LastModifiedBy
 	private String usuarioModificacion;
 	@LastModifiedDate
 	private LocalDateTime fechaModificacion;

    public TipoProductoAlmacen() {
    	// default constructor
    }

	
    public TipoProductoAlmacen(OpcionSino opcionSino, TipoProducto tipoProducto, Almacen almacen, String lote, double cantidadDisponibleActual, double cantidadBloqueada) {
        this.opcionSino = opcionSino;
        this.tipoProducto = tipoProducto;
        this.almacen = almacen;
        this.lote = lote;
        this.cantidadDisponibleActual = cantidadDisponibleActual;
        this.cantidadBloqueada = cantidadBloqueada;
    }
    public TipoProductoAlmacen(OpcionSino opcionSino, TipoProducto tipoProducto, Almacen almacen, String lote, double cantidadDisponibleActual, double cantidadBloqueada, LocalDateTime fechaExpedicion, LocalDateTime fechaVencimiento, String usuarioCreacion, LocalDateTime fechaCreacion, String usuarioModificacion, LocalDateTime fechaModificacion) {
       this.opcionSino = opcionSino;
       this.tipoProducto = tipoProducto;
       this.almacen = almacen;
       this.lote = lote;
       this.cantidadDisponibleActual = cantidadDisponibleActual;
       this.cantidadBloqueada = cantidadBloqueada;
       this.fechaExpedicion = fechaExpedicion;
       this.fechaVencimiento = fechaVencimiento;
       this.usuarioCreacion = usuarioCreacion;
       this.fechaCreacion = fechaCreacion;
       this.usuarioModificacion = usuarioModificacion;
       this.fechaModificacion = fechaModificacion;
    }
   
  @GenericGenerator(name = "tipo_producto_almacen_seq_gen", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator",
            parameters = {
                    @Parameter(name = "sequence_name", value = "tipo_producto_almacen_id_seq"),
                    @Parameter(name = "initial_value", value = "1"),
                    @Parameter(name = "increment_size", value = "1")
            })
  @GeneratedValue(generator = "tipo_producto_almacen_seq_gen")
  @Id
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    @Version
    @Column(name="version", nullable=false)
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="es_deshabilitado", nullable=false)
    public OpcionSino getOpcionSino() {
        return this.opcionSino;
    }
    
    public void setOpcionSino(OpcionSino opcionSino) {
        this.opcionSino = opcionSino;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tipo_producto", nullable=false)
    public TipoProducto getTipoProducto() {
        return this.tipoProducto;
    }
    
    public void setTipoProducto(TipoProducto tipoProducto) {
        this.tipoProducto = tipoProducto;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_almacen", nullable=false)
    public Almacen getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(Almacen almacen) {
        this.almacen = almacen;
    }
    
    @Column(name="lote", nullable=false, length=32)
    public String getLote() {
        return this.lote;
    }
    
    public void setLote(String lote) {
        this.lote = lote;
    }
    
    @Column(name="cantidad_disponible_actual", nullable=false, precision=17, scale=17)
    public double getCantidadDisponibleActual() {
        return this.cantidadDisponibleActual;
    }
    
    public void setCantidadDisponibleActual(double cantidadDisponibleActual) {
        this.cantidadDisponibleActual = cantidadDisponibleActual;
    }
    
    @Column(name="cantidad_bloqueada", nullable=false, precision=17, scale=17)
    public double getCantidadBloqueada() {
        return this.cantidadBloqueada;
    }
    
    public void setCantidadBloqueada(double cantidadBloqueada) {
        this.cantidadBloqueada = cantidadBloqueada;
    }
    
    @Column(name="fecha_expedicion", length=29)
    public LocalDateTime getFechaExpedicion() {
        return this.fechaExpedicion;
    }
    
    public void setFechaExpedicion(LocalDateTime fechaExpedicion) {
        this.fechaExpedicion = fechaExpedicion;
    }
    
    @Column(name="fecha_vencimiento", length=29)
    public LocalDateTime getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(LocalDateTime fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    
    @Column(name="usuario_creacion", length=64)
    public String getUsuarioCreacion() {
        return this.usuarioCreacion;
    }
    
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }
    
    @Column(name="fecha_creacion", length=29)
    public LocalDateTime getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(LocalDateTime fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    
    @Column(name="usuario_modificacion", length=64)
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    
    @Column(name="fecha_modificacion", length=29)
    public LocalDateTime getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(LocalDateTime fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    /**
     * toString
     * @return String
     */
     @Override
     public String toString() {
	  StringBuilder buffer = new StringBuilder();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("id").append("='").append(getId()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("opcionSino").append("='").append(getOpcionSino()).append("' ");			
      buffer.append("tipoProducto").append("='").append(getTipoProducto()).append("' ");			
      buffer.append("almacen").append("='").append(getAlmacen()).append("' ");			
      buffer.append("lote").append("='").append(getLote()).append("' ");			
      buffer.append("cantidadDisponibleActual").append("='").append(getCantidadDisponibleActual()).append("' ");			
      buffer.append("cantidadBloqueada").append("='").append(getCantidadBloqueada()).append("' ");			
      buffer.append("fechaExpedicion").append("='").append(getFechaExpedicion()).append("' ");			
      buffer.append("fechaVencimiento").append("='").append(getFechaVencimiento()).append("' ");			
      buffer.append("usuarioCreacion").append("='").append(getUsuarioCreacion()).append("' ");			
      buffer.append("fechaCreacion").append("='").append(getFechaCreacion()).append("' ");			
      buffer.append("usuarioModificacion").append("='").append(getUsuarioModificacion()).append("' ");			
      buffer.append("fechaModificacion").append("='").append(getFechaModificacion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }

	@Override
	public boolean equals(Object other) {
         if (this == other) 
         	return true;
         	
		 if (other == null) 
		 	return false;
		 	
		 if (!(other instanceof TipoProductoAlmacen)) 
		 	return false;
		 	
		 TipoProductoAlmacen castOther = ( TipoProductoAlmacen ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && (this.getVersion()==castOther.getVersion());
   }
   
   @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + (int) this.getVersion();
         
         
         
         
         
         
         
         
         
         
         
         
         return result;
   }   

  // The following is extra code specified in src/main/config/templates
// Adding extra-code
	private boolean comesFromExternalDataSource = false;
	private boolean selected;
	
	@javax.persistence.Transient
    public boolean isExternalDataSource() {
		return this.comesFromExternalDataSource;
    }

    public void setExternalDataSource(boolean value) {
        this.comesFromExternalDataSource = value;
    }

	@javax.persistence.Transient
	public boolean getSelected() {
		return selected;
	}

    public void setSelected(boolean selected) {
		this.selected = selected;
    }
    
    public void cleanPOJO() {
		if(this.opcionSino != null &&
			(opcionSino.getId() == null || this.opcionSino.getId().longValue() == 0)) {
			opcionSino = null;
		}
		if(this.tipoProducto != null &&
			(tipoProducto.getId() == null || this.tipoProducto.getId().longValue() == 0)) {
			tipoProducto = null;
		}
		if(this.almacen != null &&
			(almacen.getId() == null || this.almacen.getId().longValue() == 0)) {
			almacen = null;
		}
    }
    
    public void fillPOJO() {
		if(this.opcionSino == null) {
			opcionSino = new OpcionSino();
		}
		if(this.tipoProducto == null) {
			tipoProducto = new TipoProducto();
		}
		if(this.almacen == null) {
			almacen = new Almacen();
		}
    }
    
    public TipoProductoAlmacen createPOJO() {
		fillPOJO();
		
		return this;
	}
	
//	@PrePersist
//	public void onPrePersist() {
//		this.fechaCreacion = new Date();
//		this.usuarioCreacion = getSecurityContextPrincipal();
//	}
//
//	@PreUpdate
//	public void onPreUpdate() {
//		this.fechaModificacion = new Date();
//		this.usuarioModificacion = getSecurityContextPrincipal();
//	}
//
//	@javax.persistence.Transient
//	private String getSecurityContextPrincipal() {
//		String principal;
//		String UNKNOWN_USER = "unknownUser";
//
//		if (SecurityContextHolder.getContext().getAuthentication() == null) {
//			principal = UNKNOWN_USER;
//		} else {
//			try {
//				principal = ((User) SecurityContextHolder.getContext().getAuthentication().getPrincipal())
//						.getUsername();
//			} catch (ClassCastException e) {
//				principal = UNKNOWN_USER;
//			}
//		}
//
//		return principal;
//	}
	
  // end of extra code specified in the hbm.xml files

}

